### ISSUE TITLE
Valid package names are stored incorrectly with new version of bottle

### ISSUE THREAD

**Issue by virtuald** [pypiserver/pypiserver#102]
Not sure when this was introduced, but pypiserver 1.1.2 didn't have this issue. From the [bottle API docs](http://bottlepy.org/docs/dev/api.html#bottle.FileUpload.filename):

> Name of the file on the client file system, but normalized to ensure file system compatibility. An empty filename is returned as ‘empty’. Only ASCII letters, digits, dashes, underscores and dots are allowed in the final filename. Accents are removed, if possible. Whitespace is replaced by a single dash. Leading or tailing dots or dashes are removed. The filename is limited to 255 characters.

For example, the version `0.0.0+local` is a valid package version, but bottle gets rid of the `+`. I'm sure there are other combinations that also break.

**Comment by ankostis** [comment]
Any more patterns are highly appreciiated for  when constructing TCs.

**Comment by virtuald** [comment]
Well, [PEP 440](https://www.python.org/dev/peps/pep-0440/) has a lot to say about versioning... seems like for the most part its alpha-numeric, -, _, and +. I haven't given it a close reading.

My workaround for the moment is just to use the raw_filename from the FileUpload object. Obviously that's not a good long term solution.

**Comment by ankostis** [comment]
The latest [`v1.1.9`](/pypiserver/pypiserver/releases/tag/v1.1.9) release has upgraded *bottle* from `1.11.6 --> 1.13-dev` and this might be the cause of your problem.
