### ISSUE TITLE
Package name/version inconsistency with PyPI

### ISSUE THREAD

**Issue by stevejefferiesIDBS** [pypiserver/pypiserver#104]
I have noticed an inconsistency between pypiserver and pypi.python.org with a certain package which is fairly unusual in its naming/versioning. The package in question is python-owasp-zap-v2.4.

The package can be installed from pypi.python.org using `pip install python-owasp-zap-v2.4` resulting in an installed version of 0.0.7. The same fails on a locally deployed pypiserver as the package name appears as python-owasp-zap on this server. 

It looks as though the regex used by pypiserver is spliting (and consuming) the package name on the occurance of -v resulting in python-owasp-zap and a version of 2.4-0.0.7. Not 100% but I think a version in this format is invalid so potentially pypiserver needs a revised regex or some additional logic to check for such cases. Interestingly this worked back in older versions and looks to have been impacted by commit - 2d0de09d306e02086643580c35b94a985ea0f263

I'm open to working on providing such a fix if my above analysis makes sense and seems correct, but before I look into it I wanted to get feedback as I may have interpreted the problem incorrectly here.

**Comment by ankostis** [comment]
Yes, it seems like a bug; if you have start looking into it, please consider also #102.
Thank you in advance.
