### ISSUE TITLE
Using pypiserver with a proxy / not honoring $http_proxy or $https_proxy

### ISSUE THREAD

**Issue by Tidbits02** [pypiserver/pypiserver#105]
Hello, 

I am trying to use pypiserver infront of a firewall, they only way in and out of my network is via a proxy. The issue I am having is I dont think pypiserver is honoring the $http_proxy or $https_proxy variables on my system. I was looking through the bottel code and it looks as if there is nothing that allows it to work with a proxy, is this correct ? 

Thank you for any assitance,
Jacob

**Comment by ankostis** [comment]
`pypiserver` does not issue any requests itself; it just answers to requests made by your `pip` command.
So it is there where you should set the proxy variables.

**Comment by ankostis** [comment]
Assuming that was the problem and clossing issue.
Please reopen if my guess is invalid.
