### ISSUE TITLE
Support and test against Python 3.5

### ISSUE THREAD

**Issue by mplanchard** [pypiserver/pypiserver#108]
This should just be a matter of adding a 3.5 environment to the test suites. I've got a pypiserver running on 3.5 locally, and it works well.

**Comment by mplanchard** [comment]
Not a big enough deal to require an issue. Deleting.

**Comment by ankostis** [comment]
No prob, it is perfectly fine this issue.
I had not looked at it when I wrote about skipping issues.
Lets close it when we have merged into master.

**Comment by ankostis** [comment]
Duplicate of #110.
