### ISSUE TITLE
Provide an easy way to preload some packages that exist on pypi.python.org

### ISSUE THREAD

**Issue by ssbarnea** [pypiserver/pypiserver#133]
One of the most important advantages of having a private pypiserver is that you decouple yourself from the dependency of pypi.python.org which can go down or receive changes that may impact you.

We need a documented way to do something like:

* upload latest version of package `foobar` from pypi.python.org to our internal server
* upload foobar==1.2.3 from pypi to our internal server
* remove package version from internal server

Please note that fallback feature cannot be used because it does affect all packages. We need to be able to control what and when gets updated.

The workaround at this moment is to manually download these files from pypi and to put them on disk, which is an ugly manual process.

**Comment by bibby** [comment]
The [pypi-uploader](https://pypi.python.org/pypi/pypi-uploader) project works nicely for copying packages from pypi.python.org, and is developed with `pypiserver` in mind.

For internal packages, we're using CI to upload builds after the tests run.

`python setup.py bdist_wheel upload -r our_pypiserver`

**Comment by ssbarnea** [comment]
@bibby I am looking at the examples but I see that you do checkout the code in order to upload it which doesn't solve my problem. I think I am missing something here.

**Comment by bibby** [comment]
That's true, but it isn't always source. The distribution could be a binary dist like a wheel; but in the worst case it's still one file.

From a workstation or control machine, `pypi-uploader` first downloads a package, then uploads it to another pypiserver.

As you've stated, automatic updates can be bad; making this a manual process.

**Comment by ssbarnea** [comment]
Thank you, that' was what I was looking for. Now we only need to add this to the documentation of the pypi server too as I do see it as high likely use case.

    pip install pypiupload
    pypiupload packages mock==1.0.1 requests==2.2.1 -i internal
    pypiupload requirements requirements.txt -i internal

**Comment by ssbarnea** [comment]
Update, it seems that I reached an important bug in the pypi-uploaded -- see https://github.com/ignacysokolowski/pypi-uploader/issues/7

**Comment by ssbarnea** [comment]
Here is the solution for this problem:
```
pip install pypi-uploader
PIP_INDEX_URL="https://pypi.python.org/simple/" pypiupload packages mymissingpackage -i private
```
Which assumes that you have a `[private]` section in your `pip.conf` file.

**Comment by ankostis** [comment]
@ssbarnea can you add an example  and a  reference to `pypi-uploader` in the *"Uploading packages from sources, remotely"* and in the "Similar projects" sections respectively?

**Comment by mplanchard** [comment]
Docs added in #147
