### ISSUE TITLE
pypiserver reports 500 when it does not allow overwrite of existing package

### ISSUE THREAD

**Issue by ssbarnea** [pypiserver/pypiserver#134]
HTTP 5xx error codes do mean server side error and they are not appropriate to use when the server rejects upload of a resource because it already exists.

Based on https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error I would say that one of these would be correct:
* `403 Forbidden`
* `409 Conflict`

Here are the logs
```
2016-05-04 10:36:49,341|pypiserver._app|WARNING|140261246682880|Cannot upload 'six-1.10.0-py2.py3-none-any.whl' since it already exists!
  You may start server with `--overwrite` option.
2016-05-04 10:36:49,341|pypiserver._app|INFO|140261246682880|200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/bottle.py", line 923, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/bottle.py", line 1845, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/_app.py", line 47, in protector
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/_app.py", line 179, in update
    file_upload()
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/_app.py", line 161, in file_upload
    core.store(packages.root, uf.raw_filename, uf.save)
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/core.py", line 289, in store
    save_method(dest_fn, overwrite=True) # Overwite check earlier.
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/bottle.py", line 2447, in save
    with open(destination, 'wb') as fp:
IOError: [Errno 13] Permission denied: '/var/www/pypi/six-1.10.0-py2.py3-none-any.whl'
```

**Comment by ssbarnea** [comment]
To be clear it seems that this does happen only if the file is owned by another user, which should not be a problem because we want to be sure that pypiserver does not misbehaves and overrides the files.

So, to replicate the problem, run pypiserver at a non-root user but change the ownership of one of the files to root, allowing read to anyone. The server will run and serve the files which is as expected. What is not expected is that it does return a 500 error when you try to upload a file that already exists, even if the server is not configured to allow overwrites.

**Comment by ankostis** [comment]
So you suggest for uploads on top of files with insufficient permissions to modify the following behavior :
- if allow overwrites: 409 conflict (and some message that there is nothing the pypiserver or client can do to fix this issue)
- no-overwrites flag: 403

Correct?

**Comment by ssbarnea** [comment]
I don't mind too much about what you decide on this, as long it is HTTP compliant. 

As a new feature it would also be nice to return a 200 if the uploaded files happens to be identical with already existing one, even if overwrite option is not enabled. This would simplify usage implementations a lot as we do care only about one thing in the end: is the correct file present on the server?

**Comment by bibby** [comment]
Error `500` is the best fit for the actual issue of unsatisfied server-side file permissions. The request was ok, but the server had its own problem.

The current `409` error is also the best fit for refusal to clobber an uploaded package.

Alarm bells would raise in my organization if a `200` were given for a repeated upload. We've come to appreciate the `409`.

**Comment by magicrobotmonkey** [comment]
I agree that if the server is set to allow overwrites and can't because of system permissions, `500` seems like the best option. It's an error local to the server, not something the user caused.

**Comment by ssbarnea** [comment]
@magicrobotmonkey you are partially right, but try to see the problem from this point of view: why to return a 500 error when the user is not allowed to upload that file. The fact that the server is not able to open that file for write is just a detail in this case.

I think that the logic should be to check first if you are allowed to overwrite that file and not to try to open it for writing even if you are not supposed to write anything in it.

Anyway, that's clearly not a blocker issue but it would be nice to have it fixed in the future.

**Comment by ankostis** [comment]
Checking if *write* is permitted is not [a straight-forward operation](http://stackoverflow.com/questions/3696080/check-if-i-can-write-a-file-to-a-directory-or-not-with-python) (i.e. mounted as `ro` under unix, or permissions difficult to parse and locked files under windows) - the safest check is to actually try to *write and fail*.

I agree with @bibby & @magicrobotmonkey that
- `5xx` are for "extra-ordinary" server-problems, 
- `4xx` for client-side problems, which occasionally may require "ordinary" server-side interventions (i.e. enable a flag); the log message / http-response body should clarify those interventions, and this can be used to differentiate the responses.  

Now for the "comparison and rejection of identical packages", it is preferable to resolve it client-side, by comparing hashes, not to waste network-bandwidth.

More generally, if what you need is a "sync" operation, I would try to upload files with `rsync`, which is a tool made for this task.

**Comment by mplanchard** [comment]
I believe this has been resolved. I'm going to close this issue for now.
