### ISSUE TITLE
provide systemd service template for pypiserver

### ISSUE THREAD

**Issue by ssbarnea** [pypiserver/pypiserver#137]
Any daemon is supposed to run as a service, thus pypi-server needs a `systemd` template in order to be used as a proper services on Debian distributions (including Ubuntu).

If nobody has an already made template I will create one and contribute it.

Once this is installed people should be able to contron th pypi-server using commands line
```
service pypi-server start
service pypi-server stop
systemctl enable pypi-server
systemctl disable pypi-server
```
More information about systemd can be found at https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units

**Comment by ssbarnea** [comment]
```
# /lib/systemd/system/pypi-server.service
[Unit]
Description=pypi-server
After=network.target

[Service]
Type=simple
# systemd requires absolute path here too.
PIDFile=/var/run/pypi-server.pid
User=www-data
Group=www-data

ExecStart=/usr/local/bin/pypi-server -p 8080 -vvv -u --disable-fallback --authenticate update,download --log-file /var/log/pypi-server.log --passwords /etc/nginx/.htpasswd /var/www/pypi
ExecStop=/bin/kill -TERM $MAINPID
ExecReload=/bin/kill -HUP $MAINPID
Restart=always

WorkingDirectory=/var/www/pypi

TimeoutStartSec=3
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by mplanchard** [comment]
I agree. We could also use some documentation on how to manage its startup with supervisor, for example. I'll use your configuration script for systemd and include that information in the documentation.

**Comment by mplanchard** [comment]
See #146
