### ISSUE TITLE
package backports.shutil-get-terminal-size cannot be installed from pypiserver

### ISSUE THREAD

**Issue by ssbarnea** [pypiserver/pypiserver#138]
It seems that the `backports.shutil-get-terminal-size` package which happens to be a dependency of tornado cannot be hosted on `pypiserver`. 

While upload works, it seems that pip is not able to find it but is able to find it on public pypi.python.org

**Comment by ankostis** [comment]
@ssbarnea can you check the just released `pypiserver-1.2.0.dev1` if it fixes the dot-problem?

**Comment by ankostis** [comment]
@ssbarnea can you confirm if the fresly-released `pypiserver-1.2.0` has fixed the dot-problem?

**Comment by ankostis** [comment]
I assume this also fixed like #139.
My apologizies to ssbarnea for the notification.
