### ISSUE TITLE
no-auth upload tests hang: latest setuptools release forces password prompt

### ISSUE THREAD

**Issue by dpkp** [pypiserver/pypiserver#142]
Some failing builds:
https://travis-ci.org/pypiserver/pypiserver/builds/129511699
https://travis-ci.org/pypiserver/pypiserver/builds/126811063
https://travis-ci.org/pypiserver/pypiserver/builds/128599164
https://travis-ci.org/pypiserver/pypiserver/builds/130325284

Logs show that tests hang on a "Password:" prompt, which occurs during `python setup.py upload`

setuptools changed password prompt behavior here: pypa/setuptools#555
Change was released in v20.10.0 (about 3 weeks ago, when tests started failing).
https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v20100

see #141 for potential fix

**Comment by blade2005** [comment]
https://github.com/pypiserver/pypiserver/pull/141 has been merged. Let's closed this.

**Comment by mplanchard** [comment]
Fixed in #141
