### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by blade2005** [pypiserver/pypiserver#144]
Hey can we release a new version. My use case requires packages not be overwritten and this was fixed in https://github.com/pypiserver/pypiserver/pull/113

**Comment by mplanchard** [comment]
@ankostis Any issues with pushing a new version up to pypi? We lost some resources at work recently, so I've been super swamped (sorry!). I have tested the current release locally and am okay with releasing.

**Comment by ankostis** [comment]
Indeed now we have an opportunity window; I won't find another free slot for many weeks to come.
Please check the latest `beta-0`, and try to tag/release it, and report any difficulties, to reduce the bus-factor.

PS: Judging by the time it took us this release, we need another team-member to jump aboard :-)

**Comment by ankostis** [comment]
Also I suggest to include in this release @blade2005 work on *pam* integration: 58ac2bdfb480a.
And if it simplifies working with `/etc/password`, why not, add a new main-flag; that would be a real free-meal for linux users.

**Comment by mplanchard** [comment]
I have verified that:

- [ ] search works 
- [ ] search works with dot packages
- [ ] search requires authentication if `list` is specified in the auth list
- [ ] search does not require auth if `list` is not specified
- [ ] installing dot packages works
- [ ] installing non dot packages works
- [ ] package upload works
- [ ] uploading a package already present without specifying `overwrite` returns a 409 error
- [ ] uploading a package already present when `overwrite` is specified works as expected

**Comment by mplanchard** [comment]
My vote is that it's ready to go, and I totally agree about getting another maintainer.

**Comment by mplanchard** [comment]
@blade2005 regarding the `pam` integration in 58ac2bd, if you want to open a PR, I am happy to include it prior to releasing the current version. Otherwise, I'll push out 1.2.0 prior to heading out on vacation this Saturday, unless @ankostis has time to get it in in the upcoming week.

**Comment by blade2005** [comment]
I'll get a pr in tonight/early tomorrow

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by ankostis** [comment]
@mplanchard we've released!!!
- Thank you for the manual checks above - we have to make them one day into TCs.
- I've seen your b1 - but didn't see your tag - did you forget to ``push --tags``?

- Anyway, I'm writing down extra tasks for a release, because they are not easy to remember:
  - Copy CHANGES into the [Release-page](https://github.com/pypiserver/pypiserver/releases/tag/v1.2.0), kept TODOs, publish it, referring the new tag.
  - Rename and upload also in the release-page the generated `standalone.py` file as asset.
  - Minor edits (eg in CHANGES small formatting error) and bump version `1.2.0-->1.2.1.dev0` to be ready for more work - push as new master.
  - Close Milestone and check closed issues are appropriately marked, and if there are any open ones:
    - Issues #135, #139 are open, awaiting confirmations that bugs are fixed.

**Comment by mplanchard** [comment]
Awesome! Thanks for the rundown. I'll save this somewhere for next time.

**Comment by mplanchard** [comment]
Also, how do you feel about posting an announcement to python-announce-list? I can do the announcement, if you're interested.

**Comment by ankostis** [comment]
Very good idea.

It is just that I'm having some doubts about the redirection/normalization changes do not have caused grave mistakes, so we can wait a couole of days before amnaouncingvto catch them:

- Announce when you get back from vacations?
- Right now, if your feel confident?

**Comment by mplanchard** [comment]
I agree that it cannot hurt to wait, just in case. I'll announce when I get back, unless we have any major problems in the meantime. Thanks!
