### ISSUE TITLE
RST is broken on PyPI

### ISSUE THREAD

**Issue by roskakori** [pypiserver/pypiserver#154]
When viewing the PyPI entry at https://pypi.python.org/pypi/pypiserver the RST does not render properly and consequently the page is difficult to read.

Probably there is an RST syntax error somewhere in the README.

**Comment by ankostis** [comment]
Thanks.
It has now been fixed in PyPi - I had forgotten to update a cross-reference to a change title.

Have to add TC into TravisCI for the future.
