### ISSUE TITLE
does secure connect suppoeted?

### ISSUE THREAD

**Issue by luke0922** [pypiserver/pypiserver#159]
when using pypiserver for my personal pip server, i found i notice when i install package:
```
Downloading/unpacking redisco
  http://10.12.13.14:2345/RPC2/redisco/ uses an insecure transport scheme (http). Consider using https if 10.12.13.14:2345 has it available
  Downloading redisco-0.1.4.tar.gz
  Running setup.py (path:/home/deploy/.virtualenvs/fg/build/redisco/setup.py) egg_info for package redisco
```

can i use http  in v1.2.0?

**Comment by ankostis** [comment]
@luke0922 I'm replying to your original opening comment (copied from email):
> as issue #65 said, @ankostis said that pr was merged.
however readme does not show "-s" argument inREADME.rst

The `-s` option in #65 PR was re-named to `-a`.

**Comment by ankostis** [comment]
@luke0922 your opening-comment above is unrelated to the title of this issue.
Additionally, it is a bit difficult to make sense, maybe needs further editing, e.g. is `pypiserver` and "personal pip server " different?

**Comment by luke0922** [comment]
@ankostis i make a misunderstand for #65 , my question is that does pypiserver support https?

**Comment by ankostis** [comment]
*pypiserver* does not make any http-requests itself - it only replies to httmp-requetsts.
For the later, yes, it does support https only through some front-end server i.e. apache.

To install *pypiserver* behind apache, see the respective recipe regarding [apache `mod-wsgi`](https://github.com/pypiserver/pypiserver#apache-mod-wsgi).
The instructions for setting up apache to server https is beyond this projects; look at the [Let's Encrypt* project](https://letsencrypt.org/).

**Comment by luke0922** [comment]
ok， got it, maybe i should close this issue now.
