### ISSUE TITLE
Pypi behind proxy

### ISSUE THREAD

**Issue by ITler** [pypiserver/pypiserver#160]
Hy folks,

I would like to run my pypiserver behind a nginx proxy (reverse proxy). 
Accessing pypiserver *directly* (using `pip3 install --extra-index-url http://pypiserver.example.com:12345 moduletest` on a client) works fine.

Proxied browsing through the repository using a browser (i.e. `http://myproxy.example.com/simple/moduletest`) works fine. `Nginx conf`:

    upstream pypi {
      server pypiserver.example.com:12345 fail_timeout=0;
    }

    server {
      server_name myproxy.example.com;

      location / {
        proxy_set_header  Host $host;
        proxy_set_header  X-Real-IP $remote_addr;
        # no effect: proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        # no effect: proxy_set_header  X-Forwarded-Proto $scheme;
        proxy_pass http://pypi;
      }
    }

Obviously pip is not able to find any package when accessing pypiserver via *proxy*, like `pip3 install --extra-index-url http://myproxy.example.com moduletest` on a client, returning:

    Could not find a version that satisfies the requirement moduletest (from versions: )
    No matching distribution found for moduletest

I assume, that's a newbie issue? I'd appreciate your support.

Thank you
ITler

**Comment by ankostis** [comment]
Hi @ITler, have no experience with *nginx*, but I want to help you fix it, as this would make [a good recipe](https://github.com/pypiserver/pypiserver/#recipes).

Can you give your try the same *pip* commands adding verbose flags, like that:

    pip3 -vvv install --extra-index-url ...

**Comment by ITler** [comment]
Thanks for your response. The `-vvv` reveals a few details that pointed me to the right direction.
The header definition was not perfect. It is:

    upstream pypi {
      server              pypiserver.example.com:12345 fail_timeout=0;
    }

    server {
      server_name         myproxy.example.com;

      location / {
        proxy_set_header  Host $host:$server_port;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_pass        http://pypi;
      }
    }

**Comment by ankostis** [comment]
@ITler would you mind sharing the *ngnix* config here, along worth some minimum instructions on how to set it up?

**Comment by ITler** [comment]
I'm having trouble to get formatting correct. When pasting code to README.rst, it is quoted but not codeblocked, see [here](https://github.com/ITler/pypiserver/tree/ITler-patch-1#behind-a-reverse-proxy).
Don't know why. Even manual typing leads to same effect. What am I doing wrong? I use github to edit directly. Maybe take the text and paste it yourself... Might be faster.

**Comment by ankostis** [comment]
It is not Markdown but [ReStructured Text](http://docutils.sourceforge.net/docs/user/rst/quickstart.html#preformatting-code-samples).
So you need to end the previous sentence with double `::` in addition to indentation.

If you manage it, you may place your recipe in the same level as [apache-receipe](https://github.com/pypiserver/pypiserver/blob/master/README.rst#apache-mod_wsgi), directly below it.

In any case, thank you for your efforts.

**Comment by ITler** [comment]
I managed to get formatting right. However, placing this at same level like apache-receipe would be wrong because this is the level 'alternative WSGI server'. My topic is 'reverse proxy', which is totally different. BTW, you could do reverse proxying with apache, too (don't know how). My text is placed at correct level and configuration is quite basic. You could merge.

**Comment by ITler** [comment]
I managed to get formatting right. However, placing this at same level like apache-receipe would be wrong because this is the level 'alternative WSGI server'. My topic is 'reverse proxy', which is totally different. BTW, you could do reverse proxying with apache, too (don't know how). My text is placed at correct level and configuration is quite basic. You could merge.

**Comment by ankostis** [comment]
Reverse-proxying with *Apache* meshes up with the paths(#155), so it should be avoided; wsgi is safer choice.
I expect *ngnix* to have the same problem; if you bump into it, please report it.

**Comment by ITler** [comment]
Yeah, I would expect that, too. However in "my" setup, I don't use custom paths, but I'll keep my eyes open. I presume, that filtering the Request URI before proxying by removing the custom location part, could help to avoid this issue, but I'm not that experienced with that topic.
