### ISSUE TITLE
Upload Size is too small for larger repositories

### ISSUE THREAD

**Issue by johnpneumann** [pypiserver/pypiserver#164]
Due to the size restrictions within the `MEMFILE_MAX` setting within bottle, larger packages like [numpy](https://pypi.python.org/pypi/numpy/1.12.0b1) and [pandas](https://pypi.python.org/pypi/pandas/0.19.1) (or even Django) aren't able to be included as package dependencies when using pypiserver. Is there any chance that either A) This behaviour can change; or B) That you would accept a pull request with a fix for this? As it stands `request` simply inherits directly from `LocalRequest`, so simply importing `LocalRequest`, subclassing it and then allowing the change to happen from an environment variable would be perfect. I've done as much in my own fork, but would rather have this be part of the mainline. 

Relevant changes can be found from [here](https://github.com/johnpneumann/pypiserver/blob/allow_larger_uploads/pypiserver/_app.py#L11) and [here](https://github.com/johnpneumann/pypiserver/blob/allow_larger_uploads/pypiserver/_app.py#L36-L40). I admit that I'm not a huge fan of just dropping request in and calling the `PyPiRequest`, but my thought process was that it was the most minimally invasive way of doing this. 

I can make it a PR, but thought I'd add an issue before doing so.

**Comment by ankostis** [comment]
Thank you for bringing this up.

Have you tried something fixing it with a more [straight forward monkey-patching](http://stackoverflow.com/a/16866126/548792)?
But the real issue is that it **shouldn't fail**, even if `len(package) > MEMFILE_MAX`.

Would it be possible to send the traceback of the error?
Greatly appreciated if you can provide a failing test-case.


By the way, that was a very kind way of asking things :-)

**Comment by johnpneumann** [comment]
I had not tried the monkey-patching route, but will do that and see if there are any notable differences. And yes, I will get a use case together and get the full traceback for you shortly.

**Comment by johnpneumann** [comment]
So after running this through the ringer and attempting to repro this, it appears that this isn't an issue. My guess is that the issue was with the Nginx configuration and not the `MEMFILE_MAX` setting. If for some reason, I missed a step in trying to repro the issue, I'll reopen with the full details on how to repro the issue. Apologies for the noise. :)
