### ISSUE TITLE
Installing a pypiserver-hosted package from within a requirements.txt file fails, but doing so from the command line works.

### ISSUE THREAD

**Issue by dougthor42** [pypiserver/pypiserver#168]
First I'd like to say that I haven't been able to verify that this is *not* an issue with `pip` itself, so I'm sorry if it's on their end and not yours.

## Summary
Installing a `pypiserver`-hosted package from within a `requirements.txt` file fails, but doing so from the command line works.

## Versions
+ Python 3.5.2, 64-bit
+ Pip 9.0.1
+ pypiserver 1.2.0
+ OS: Windows 10 AU (running WinPython 3.5.2.2)

## Steps to Reproduce
1. Set up a `pypiserver` host and upload a package to it. For this example, we'll use a package called `gdw`
2. Create a clean venv locally and update `pip` to 9.0.1.
3. **Test Case 1:** From command line.
    + `python -m pip install gdw --index-url http://my_pypi.local/pypi`
    + Result: Complains about https, as expected.
    + `python -m pip install gdw --index-url http://my_pypi.local/pypi --trusted-host my_pypi.local`
    + Result: Success!
    + Remove the installed package: `python -m pip uninstall -y gdw`
4. **Test Case 2:** From requirements file.
    + Create a requirements.txt file with a single line: `gdw --index-url http://my_pypi.local/pypi`
    + `python -m pip install -r requirements.txt`
    + Result:
        ```
        Could not find a version that satisfies the requirement gdw (from -r requirements.txt (line 1)) (from versions: )
        No matching distribution found for gdw (from -r requirements.txt (line 1)
        ```
5. **Test Case 2b:** Maybe it doesn't like non-https and Pip is not raising that warning.
    + `python -m pip install -r requirements.txt --trusted-host my_pypi.local`
    + Result: Same thing
6. **Test Case 2c:** Well what if we put `--trusted-host` in the requirements file?
    + Change `requirements.txt` to `gdw --index-url http://my_pypi.local/pypi --trusted-host my_pypi.local`
    + `python -m pip install -r requirements.txt`
    + Result: same as before.

## Comments
According to pypa/pip#3007, it *should* accept `--trusted-host` inside of requirements files. However, comments in [pip#3799](https://github.com/pypa/pip/issues/3799#issuecomment-228840598) imply that it doesn't do the same thing as the command line option...

Here's an image of the PyPIServer index, so you can see that it has a version of `gdw` to pull (also the fact that Test Case 1 worked provides this info).
![image](https://cloud.githubusercontent.com/assets/5386897/23141782/4fff5df6-f76d-11e6-8d0d-09c2147efec8.png)

---

So, any thoughts on what this issue might be? Should I report this to the `pip` maintainers? I haven't been able to reproduce it without using `pypiserver` because I don't know of any other package indexes to use for `--index-url`.

Thanks,

**Comment by dougthor42** [comment]
It looks like I was just not using the `requirements.txt` file correctly...

Instead of putting the `-index-url` inline with the package, I should have it on its own line.

```
--trusted-host my_pypi.local
--index-url http://my_pypi.local/pypi
gdw
```

Now I feel foolish. :sweat:

Sorry for the noise!

**Comment by mplanchard** [comment]
No worries! Thank you for the report, and I'm glad it turned out to be nothing.
