### ISSUE TITLE
pip search handled?

### ISSUE THREAD

**Issue by mforkel** [pypiserver/pypiserver#170]
I tried to run pypiserver as described in the README. But the POST request issued by `pip search`, which is used as an example in section "Quickstart: Installation and Usage", does not seem to be handled by pypiserver: I got an HTTP error 405. Accordings to section "Known Limitations", only `pip install` is handled. If the search command should be handled, what might have gone wrong in my test installation? Otherwise, I would suggested to update section "Quickstart: Installation and Usage".

**Comment by mplanchard** [comment]
Which version of `pypiserver` are you running?

Support for `pip search` was added in #114, which I believe went out with `1.2.0`. If it's not working we need to look into it. We should also remove that section from the "Known Limitations".

**Comment by mforkel** [comment]
The version I'm running is `1.2.0`. I downloaded `pypiserver-1.2.0.zip` from PyPi and I just checked the value of `__version__` in `__init__.py`.

**Comment by mforkel** [comment]
After looking at #114, I found that one can use
```
pip search --index http://localhost:8080 ...
```
instead of 
```
pip search --index http://localhost:8080/simple/ ...
```
as the README suggests, or
```
pip search --index http://localhost:8080/ ...
```

**Comment by mplanchard** [comment]
I've opened a PR up to fix the issues you brought up. Thanks for bringing them to our attention!
