### ISSUE TITLE
Spurious blanks in _app.log_request

### ISSUE THREAD

**Issue by mforkel** [pypiserver/pypiserver#171]
There are some spurious blanks in `_app.log_request`:
```
diff --git a/pypiserver/_app.py b/pypiserver/_app.py
index 02ad3da..55e5cca 100644
--- a/pypiserver/_app.py
+++ b/pypiserver/_app.py
@@ -56,7 +56,7 @@ class auth(object):
 
 @app.hook('before_request')
 def log_request():
-    log.info(config.    log_req_frmt, request.environ)
+    log.info(config.log_req_frmt, request.environ)
 
 
 @app.hook('after_request')
```

[Edit] That kind of whitespace seems to be syntactically ok. I didn't find a direct reference to it in [PEP8](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements). But it sure looks strange to me...

**Comment by mplanchard** [comment]
Looks like you've already got a diff for the fix. Want to open a PR?

**Comment by mforkel** [comment]
Sorry, I don't have a GitHub repository for this. Could you use the above patch?

**Comment by mplanchard** [comment]
Happy to! I'll get that in sometime today.

**Comment by blade2005** [comment]
@mplanchard From the looks of it @ankostis made that change probably a year ago in https://github.com/pypiserver/pypiserver/commit/8a8d9e4f16ed621eb359c660d32f661faecf4460

Could just be a case of search and replace screw up, but testing and/or asking @ankostis about that change would be a good idea. (or both i like both)

**Comment by mforkel** [comment]
@mplanchard Thanks!
