### ISSUE TITLE
Upload results in server error

### ISSUE THREAD

**Issue by mforkel** [pypiserver/pypiserver#174]
I'm running pypiserver 1.2.0 on Raspbian Jessie without authentication:
```
# pypi-server -p 8080 -P .  -a . -v --log-file /var/log/pypiserver/pypiserver.log /var/www/pypi
```
Trying to upload as described in the README at "[Upload with setuptools](https://github.com/pypiserver/pypiserver#upload-with-setuptools)" results in a server error
```
$ python setup.py sdist upload -r local
...
running upload
Submitting dist/package-0.2.0.tar.gz to http://pypi.host.lan:8080
Upload failed (500): Internal Server Error
error: Upload failed (500): Internal Server Error
```
while the server's log says
```
<LocalRequest: POST http://pypi.host.lan:8080/>
200 OK
```

**Comment by mforkel** [comment]
Sorry, my fault. `www-data` didn't have write permission for the server's directory.

**Comment by mplanchard** [comment]
Thanks for the update! I'm going to close this for now. Please feel free to comment if something changes.
