### ISSUE TITLE
Updating to new bottle version

### ISSUE THREAD

**Issue by sideffect0** [pypiserver/pypiserver#176]
Why `bottle.py` old version is used ?

**Comment by mplanchard** [comment]
Hi @sideffect0. Thanks for your question! 

Pypiserver uses an integrated version of bottle to ensure compatibility and to avoid any issues with dependencies. We do update it from time to time, but generally only when the base package functionality requires such an update or for security reasons. If you would like to use another web server (including another version of bottle), please see [our documentation on the subject](https://github.com/pypiserver/pypiserver#using-a-different-wsgi-server).

Is there any particular functionality that you're looking for in a newer version of bottle that isn't provided with the current one?

**Comment by mplanchard** [comment]
Given the lack of response, I'm going to close this for now. Please feel free to respond if you don't feel like your question was answered.
