### ISSUE TITLE
Update default fallback URL to https, since PyPI has begun returning 403 for http connections

### ISSUE THREAD

**Issue by MikeSchneeberger** [pypiserver/pypiserver#179]
With the following PIP configuration ...

pip.ini:
```
[global]
index-url = http://[IP OF PYPI SERVER]:8080/simple/

[install]
trusted-host = [IP OF PYPI SERVER]
```

... I get the following output on the command prompt, when trying to install a package that is not on the pypi server.

Command Prompt (Windows):
```
([PATH TO MY ENV]) [CURRENT PATH]>pip install -v paramiko
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting paramiko
  1 location(s) to search for versions of paramiko:
  * http://[IP OF PYPI SERVER]:8080/simple/paramiko/
  Getting page http://[IP OF PYPI SERVER]:8080/simple/paramiko/
  Starting new HTTP connection (1): [IP OF PYPI SERVER]
  http://[IP OF PYPI SERVER]:8080 "GET /simple/paramiko/ HTTP/1.1" 303 0
  Starting new HTTP connection (1): pypi.python.org
  Incremented Retry for (url='/simple/paramiko/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0424D6B0>, 'Connection to
pypi.python.org timed out. (connect timeout=15)')': /simple/paramiko/
```

I would expect that it downloads the package from the pypi.python.com server, if it doesn't find it on the pypi server. But unfortunately I get a timeout error message. How can I make it work?

**Comment by mplanchard** [comment]
Looks like pypiserver is behaving properly here. It's returning a redirect to `pypi.python.org`, but that's timing out. Can you verify that you can access `http://pypi.python.org/simple/paramiko` via curl or `requests` from the computer making this request?

You might consider updating your version of pip if possible. Looks like those debug messages about the Python ABI were addressed [here](https://github.com/pypa/pip/issues/3383).

**Comment by MikeSchneeberger** [comment]
The curl command gives me the following outputs:

```
(C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv) C:\Users\[USER]\Documents>curl https://pypi.python.org/simple/paramiko

(C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv) C:\Users\[USER]\Documents>curl http://pypi.python.org/simple/paramiko
curl: (7) Failed to connect to pypi.python.org port 80: Timed out
```

The "https" connection works, whereas the "http" doesn't.

I have pip version 9.0.1, which is the current version.

```
(C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv) C:\Users\[USER]\Documents>pip --version
pip 9.0.1 from C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages (python 3.6)
```

**Comment by mplanchard** [comment]
Hm. I'm able to hit the `http` endpoint (it redirects to the `https` endpoint). Seems like your system isn't following the 301 redirect?

```
(Python36) [Nautilus@Nautilus-2 ~]$ curl -v http://pypi.python.org/simple/paramiko
*   Trying 151.101.192.223...
* TCP_NODELAY set
* Connected to pypi.python.org (151.101.192.223) port 80 (#0)
> GET /simple/paramiko HTTP/1.1
> Host: pypi.python.org
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: Varnish
< Retry-After: 0
< Location: https://pypi.python.org/simple/paramiko
< Content-Length: 0
< Accept-Ranges: bytes
< Date: Thu, 05 Oct 2017 14:42:42 GMT
< Via: 1.1 varnish
< Connection: close
< X-Served-By: cache-dfw18639-DFW
< X-Cache: HIT
< X-Cache-Hits: 0
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: none
<
* Closing connection 0
```

I'm not sure how to help you troubleshoot this, as I'm not very familiar with Windows. However, if you can't fix your system failing to follow the redirect, you could specify the fallback URL as `--fallback-url "https://pypi.pyhton.org/simple/"`

**Comment by MikeSchneeberger** [comment]
Yes, you are right. The following code solves the problem.

`pypi-server --fallback-url https://pypi.python.org/simple/ -p 8080 -P C:\Data\htpasswd C:\Data\packages`

Why is "http://pypi.python.org/simple/" selected as the standard fallback url, and not "https://pypi.python.org/simple/"?

**Comment by mplanchard** [comment]
PyPI didn't always perform the automatic redirect to the SSL-enabled site, and prior to Python 2.7.9 and 3.4, SSL connections were much flakier in Python. It's probably not a bad idea to update our default fallback URL, given that PyPI is now permanently redirecting.

**Comment by alexntt** [comment]
This is now a bigger issue, as we are seeing:

```
HTTPError: 403 Client Error: SSL is required for url: http://pypi.python.org/simple/pytest-cov/
```

and similar, pypi seems to be rejecting http requests, not redirecting

**Comment by mplanchard** [comment]
Well, that's frustrating. They're still redirecting for the root `http://pypi.python.org`. It's been busy at my day job, but I will try to push this up the priority queue. In the meantime, please specify `https://pypi.python.org` for the `--fallback-url` when starting/configuring pypiserver.

**Comment by alexntt** [comment]
Much appreciated- we've been able to hack that, at this point it's not urgent for us- it's just nice to have (and still, it needs to trickle down to https://github.com/codekoala/docker-pypi/pull/6 ), but your promptness is much appreciated

**Comment by natefoo** [comment]
[Here's the announcement about it](https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html) including the rationale for the change.

**Comment by jkpubsrc** [comment]
I used `extra-index-url` in `/etc/pip.conf` in order to specify my own server. If I do that now downloads of regular packages fail because then - and only then - pip uses `http` instead of `https` to connect to `pypi.python.org`. Has this behaviour something to do with this issue?

**Comment by mplanchard** [comment]
@jkpubsrc just to clarify, is that behavior occurring with the `--falback-url` to `https://pypi.python.org/simple/` on your pypiserver?

**Comment by jkpubsrc** [comment]
No. I was researching about this problem I was talking about and considered it as a bug in pip. I just learned about this issue here in pypiserver now and now I try to understand if this bug is related to that. I have a clear understanding of how I'd implement pip or even pypiserver but I have the feeling that pip and the package management system behind it might be quite different than I thought. See: https://github.com/pypa/pip/issues/4823

The preferred model would be for pip to download package lists from different servers, merge them (by priority to circumvent package name conflicts) and then do every required task based on this list. Installing would require to select dependencies and then download them in the correct order. Both bugs somehow indicate that pip does not follow this clear model. If pypiserver gives pip an alternative download url - that's what you probably do by providing `--fallback-url` - this would indicate that the current architecture is quite different how I think it should be. I'm now happy to learn about where these differences exactly are in order to understand pypiserver and pip better. I've not enough information for any clear understanding. And that's why I ask. So please tell me if and where I'm wrong with my ideas/assumptions. You've more insight into this, I still don't know enough about pypiserver and pip and the architecture of these pieces of software.

Thank you!

**Comment by hodgestar** [comment]
Bumping this as fairly urgent. :)

**Comment by hodgestar** [comment]
Should be a two character PR (one to add an 's' to the code and another to add an 's' to the tests).

**Comment by mplanchard** [comment]
@hodgestar I appreciate the urgency, but there is a workaround in the meantime. There have also been failures in our automated test suite that need to be resolved prior to pushing a new version (there is an open issue to investigate these). As I am sure you can appreciate, no one pays me or @ankostis to work on this, so unfortunately it has to wait for when time allows. I promise it is at the top of my queue of things to do outside of my day job.

**Comment by mplanchard** [comment]
That being said, I will try to at least get a fix into master today! 😁

**Comment by hodgestar** [comment]
Yay! Thank you! :D

**Comment by hodgestar** [comment]
:cake: :cake: :cake: :smile_cat:

**Comment by mplanchard** [comment]
This is now in master. Please feel free to install directly from there if you need to while we prepare a release.

**Comment by ankostis** [comment]
@mplanchard would it make sense to release `1.2.0.post0` (hat's a final release, so no `pip --pre` needed) with just this blocker, fixed?
And have more time to fix more stuff in 1.2.1?

**Comment by alexntt** [comment]
I'm not sure, I think I've hit https://github.com/pypiserver/pypiserver/issues/175 , so the `--pre` version seems to have issues. If those are widespread problems on `--pre`, I think you're better off specifying the fallback URL via the CLI rather than using the `--pre` version.

**Comment by ankostis** [comment]
But does #175 affect also the old `v1.2.0`?

**Comment by alexntt** [comment]
I don't think so- we were running it and never had an issue, I think.

**Comment by mplanchard** [comment]
I think #175 and #186 may be the same thing, both of which stem from #132. I'm definitely willing to release a patch just for the fallback URL. We could also back out #132 and make it 1.2.1dev1, which will give us more time to resolve the issues with it.
