### ISSUE TITLE
Dual-mode authenticate appears broken

### ISSUE THREAD

**Issue by jameshiebert** [pypiserver/pypiserver#186]
We have a deployment of pypiserver where we want to password protect updates, but want to leave download and list operations public. The docs (e.g. ``$ pypi-server --help``) say:

> For example to password-protect package downloads (in addition to uploads)
> while leaving listings public, give:
> -P foo/htpasswd.txt  -a update,download

I conclude from that statement that we should use "-P foo/htpasswd.txt  -a update". Is this correct? With this config, I would expect to be able to browse to https://localhost:[port]/simple with no authentication but need auth to register/submit packages. However, on the current master, using these settings, trying to browse to this URL, I get a HTTP 401.

I put together a quick test case (below) based on your great test suite to check these assumptions and ran a git bisect between v1.2.0 and master.

```bash
$ git bisect start HEAD v1.2.0 --
$ git bisect run ./script.sh
3d37c009997ec8f199e54524641726fea260906e is the first bad commit
commit 3d37c009997ec8f199e54524641726fea260906e
Author: Kyle Hornberg <kyle.hornberg@gmail.com>
Date:   Fri Apr 29 07:35:46 2016 -0500

    Add matrix auth

:040000 040000 bdddda1c65ca6fad7fafd944467db5d402931477 424a7dd7630432581a3c8f454036598c741f5074 M	pypiserver
:040000 040000 a962432e4cae100dceba73d35bcae12ed79f8f9e 7c047a288d92226aa2fd13be80ad0b9cd722d5b9 M	tests
bisect run success
```

Looks like the addition of the matrix auth broke some functionality the the classic list-based auth config? Is there a way to accomplish the config behavior that we want using the matrix auth style?

Cheers,

~James

script.sh:
```bash
#!/bin/bash

py.test -k stuff
```

tests/test_stuff.py
```python
import contextlib
import subprocess
import time
import sys
from urllib.request import urlopen
from textwrap import dedent

import pytest

from .test_server import _build_url, empty_packdir, port, _BUFF_SIZE, _port, \
    SLEEP_AFTER_SRV, Srv, _kill_server, project, package, pypirc_file, chdir, \
    _run_python


def _run_server(packdir, port, authed, other_cli=''):
    pswd_opt_choices = {
        True: "-Ptests/htpasswd.a.a -a update,download,list",
        False: "-P. -a.",
        'partial': "-Ptests/htpasswd.a.a -a update"
    }
    pswd_opts = pswd_opt_choices[authed]
    cmd = "%s -m pypiserver.__main__ -vvv --overwrite -p %s %s %s %s" % (
        sys.executable, port, pswd_opts, other_cli, packdir)
    proc = subprocess.Popen(cmd.split(), bufsize=_BUFF_SIZE)
    time.sleep(SLEEP_AFTER_SRV)
    assert proc.poll() is None

    return Srv(proc, int(port), packdir)


@contextlib.contextmanager
def new_server(packdir, port, authed=False, other_cli=''):
    srv = _run_server(packdir, port,
                      authed=authed, other_cli=other_cli)
    try:
        yield srv
    finally:
        _kill_server(srv)


@pytest.mark.parametrize("pkg_frmt", ['bdist', 'bdist_wheel'])
def test_setuptoolsUpload_partial_authed(empty_packdir, port, project, package,
                                 pkg_frmt, monkeypatch):
    url = _build_url(port)
    with pypirc_file(dedent("""\
            [distutils]
            index-servers: test

            [test]
            repository: %s
            username: a
            password: a
        """ % url)):
        with new_server(empty_packdir, port, authed='partial'):
            with chdir(project.strpath):
                cmd = "setup.py -vvv %s register -r test upload -r test" % pkg_frmt
                for i in range(5):
                    print('++Attempt #%s' % i)
                    assert _run_python(cmd) == 0
            time.sleep(SLEEP_AFTER_SRV)
    assert len(empty_packdir.listdir()) == 1


# Ensure that we can hit the package listing without any authentication
def test_authed_upload_open_download(empty_packdir, port):
    url = _build_url(port) + '/simple'
    with new_server(empty_packdir, port, authed='partial'):
        resp = urlopen(url)
        assert resp.getcode() == 200
```

**Comment by mplanchard** [comment]
Thanks for the report and the test case! I will look into integrating the test case into the test suite and determining why the expected functionality isn't working

**Comment by jameshiebert** [comment]
Cool, thanks!

**Comment by mplanchard** [comment]
Indeed, reverting #132 brings these tests from failing to passing. I have performed the reversion on https://github.com/mplanchard/pypiserver/tree/revert-matrix-auth and am adapting these tests into that branch to ensure that we do not revert to the failure case.

**Comment by ankostis** [comment]
Just to state that my gut feeling about #132: it seems to be very case-specific and constrained.
A better alternative would be, as @bibby [suggested](https://github.com/pypiserver/pypiserver/pull/132#issuecomment-215977004), to become a separate project providing an `auther`  - we have the API, we need to make it into a setuptools entry-point.

So i vote not to hurry to release with it.

**Comment by mplanchard** [comment]
Agreed. I am cleaning up @jameshiebert's tests and getting a PR ready to revert #132 for the moment.

**Comment by bibby** [comment]
Reacquainting myself with the issue, I still like the idea of a pluggable auther module. That way, users can select the authentication that's right for them (and the deps they bring): htpasswd, LDAP, OAuth2 [Github, Gitlab], or a custom solution. 

Writing modules for uncommon auth strategies is a good way for users to contribute.

**Comment by mplanchard** [comment]
@jameshiebert please try the current `1.2.1rc0` release and see if this issue is resolved. Thanks!

**Comment by jameshiebert** [comment]
@mplanchard Yeah, that seems to work for me. Thanks for the fast action!
