### ISSUE TITLE
proxy support [was: pypi-server -U fails with socket.error: [Errno 10060]]

### ISSUE THREAD

**Issue by alexandrul** [pypiserver/pypiserver#19]
`pypi-server -U [OPTIONS] [PACKAGES_DIRECTORY]` seems to fail due to lack of proxy support. I have tried to set `http_proxy` but it has no effect. pip is working fine with the proxy.

**Comment by ankostis** [comment]
So @schmir the only file involved with this is ``pypiserver/manage.py``, right?
Would you mind describing what problems you bumped into, in python-3?

**Comment by schmir** [comment]
I don't remember any specific problem. Sorry.

**Comment by ankostis** [comment]
After searching a couple of days, I'm giving up on this :-(
[branch: ankostis/pypiserver@proxy_rpc](/ankostis/pypiserver/tree/proxy_rpc)

Pyhon's XML-RPC support across version is very unstable.  This fact, combined with PyPi-server's well-known network problems, makes the time required to ensure a stable and tested implementation disproportionately high compared to the benefits from utilizing an http-proxy when running the ``-U`` command. 

I note that this *check-for-updates-on-all-uploaded-packages* command is not necessary for the core service offered by this project, and any dependencies (i.e. the `requests` library) would make sense if more XML-RPC PyPi-API functionality is planned (which is not).
