### ISSUE TITLE
End Explicit Support for Python 3.3

### ISSUE THREAD

**Issue by mplanchard** [pypiserver/pypiserver#192]
Python 3.3 has been EoL'ed since September, and more and more major packages are dropping support, making maintenance more difficult. Pytest, for example, [dropped support in version 3.3.0](https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#pytest-330-2017-11-23).

I think that unless there is a really good reason, we should stop explicitly supporting Python 3.3 going forward.

**Comment by ankostis** [comment]
+1

**Comment by hugovk** [comment]
+1

Here's the pip installs for pypiserver from PyPI for the last month (via `pypinfo --percent --pip pypiserver pyversion`), showing no Python 3.3.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   91.4% |         11,191 |
| 3.6            |    3.3% |            408 |
| 2.6            |    2.8% |            343 |
| 3.5            |    2.3% |            281 |
| 3.4            |    0.1% |             18 |
| 3.2            |    0.0% |              2 |

**Comment by mplanchard** [comment]
That's really interesting, thank you! I'm not surprised the 2.7 percentage is higher than the 3 percentage, but I am surprised it's as high as it is. Hopefully the 3 percentage increases in the next couple of years before the EoL of Python 2.7.

**Comment by hugovk** [comment]
Please see PR #198.
