### ISSUE TITLE
Problem synchronizing index and package while removed

### ISSUE THREAD

**Issue by gokuatkai** [pypiserver/pypiserver#200]
Hello, 
We are serving thousands of packages using pypiserver since last past years. But we were suffering from very slow response and intensive CPU usage while serving our requests due to the index being rebuilt often on requests (using --upgrade etc..).
Then we decided to use what the documentation says: installing `pypiserver[cache]`, using nginx cache and even disabling the hash algo checks, and it is incredibly speeding up our `pip install` commands. 10 times faster !

But on the other side we have seen that using twine to push new package did not refresh the index. So basically our files were on the disk, but not shown on the pypiserver, and `pip install` failed claiming that such version did not exist. 
So I dug a bit in the code, in `default_conf()` and I found `cache_control` parameter, which I have set to `20` seconds. It seems to help, like every 20seconds or so the newly packages appear and are able to be served and installed.

The problem is while removing packages, either with curl (using `--form ":action=remove_pkg" ...` or deleting directly from the disk does not make the package disappear from the http UI, and the link goes to a 404 error page. More over, using many processes/threads, does a weird thing, sometimes it will show the link of the missing package and after a refresh (session changed to other process/thread I guess) the package is not there anymore, and its toggling like that on each refresh of the page. Once its there once its not, but the `pip install ` with this package would failed with 404.

I am using pypiserver 1.2.0 and Python 2.7.6. The app() is called by uwsgi as follow:
```
# bb_pypiserver/wsgi.py
wsgi_app = app(
    root=sys.argv[1],
    hash_algo=None,
    redirect_to_fallback=False,
    password_file='/etc/nginx/conf.d/htpasswd',
    fallback_url=False,
    authenticated=['list', 'download', 'update'],
    cache_control=20
)
```
And the uwsgi command
```
uwsgi --need-app --wsgi-file=bb-pypiserver/lib/python2.7/site-packages/bb_pypiserver/wsgi.py \
    --callable=wsgi_app --pyargv=/path_to_packages --socket=127.0.0.1:9084 \
    --master --processes=8 --threads=4 
```

Would you have an idea how to deal with this strange delete behavior?

Thanks.

**Comment by gokuatkai** [comment]
We have been playing around since, and made a lot of debug, it seems that the events are not dispatched from watchdog like the queue is not consumed. Or that it cannot retrieve the tuple from it.
this caching with caching does not at all for us

**Comment by mplanchard** [comment]
Glad to know that pypyiserver is (mostly) working for you guys!

So one of the things that makes this complicated to debug is the potential multiple layers of caching. There's a lot of fine tuning that can be done at each layer to best suit your use case.

You mentioned you're using nginx. Do you have it set up as a reverse proxy? Could you paste your nginx config here, minus any sensitive information?

**Comment by gokuatkai** [comment]
Hello @mplanchard thanks for your reply here is the proxy config, nothing fancy:
`
upstream backend-dev {
    server localhost:9083 max_fails=0 fail_timeout=0;
}

server {
    server_name cheeseshop-dev.myserver.com;
    listen      80; # Yes we dont use https yet

    access_log  /var/log/nginx/cheeseshop-dev.myserver.com-access.log;
    error_log   /var/log/nginx/cheeseshop-dev.myserver.com-error.log;

    location / {
        auth_basic              "Restricted";
        auth_basic_user_file    /etc/nginx/conf.d/htpasswd;
        include                 /etc/nginx/proxy.conf;
        proxy_pass              http://backend-dev;
    }
}
`

**Comment by gokuatkai** [comment]
Actually we solved the problem. We used uWSGI to thread the app, and adding `--lazy-app` let the app manage the queue thread properly. Thanks tho!
