### ISSUE TITLE
Test upcoming Twine release (1.10.0rc1)?

### ISSUE THREAD

**Issue by brainwane** [pypiserver/pypiserver#203]
https://test.pypi.org/project/twine/1.10.0rc1/  is a release candidate for Twine 1.10.0 which I'm planning to release early this week. Please see the [changelog](https://twine.readthedocs.io/en/latest/changelog.html) for detailed notes under "Next feature release".

I believe this is how you test it out on its own:  `pip install --upgrade --pre --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple twine` 

I would to hear about any problems this new release causes in `pypiserver`. And if there are some simple tests I can run before a new release to check whether a change in `twine` would break core functionality for you, maybe you could mention that on pypa/twine#314.

(By the way, I also work on [Warehouse](https://github.com/pypa/warehouse/), the new codebase for https://pypi.org, and [your list of similar projects in the `README`](https://github.com/pypiserver/pypiserver#similar-projects) has been helpful to me! And I thought you might want to know about pypa/warehouse#3123 since it's about how your project's metadata renders on the new pypi.org.)

Thanks.

**Comment by mplanchard** [comment]
Thanks so much for reaching out!! I'm really glad to be able to collaborate to make sure that our users aren't adversely affected by updates. 

I just moved on Friday, so things are a bit hectic around the house, but I will make it my top priority this week to find some time both to contribute to pypa/twine#314 and to run our full test suite against the RC.

And thanks for the heads up about pypa/warehouse#3123! I am personally very much looking forward to Warehouse's full rollout. From what I've seen, it's going to be a major improvement on the existing PyPI site.

Anyway, I'll get on this hopefully tonight or tomorrow night at the latest, and I'll post updates both here and in pypa/twine#314.

**Comment by ankostis** [comment]
@mplanchard you may remove both our names and put yours as maintainer.

**Comment by mplanchard** [comment]
@brainwane our existing test suite performs a twine upload, so I just added a tox environment in #204 that can be manually run to test with the current pre-release of twine against all supported Python runtimes with `tox -e pre_twine`. All of the tests passed with no problems on my local machine against the current twine RC, so seems like we're good to go!

**Comment by brainwane** [comment]
Thank you very much for the advice and the testing! https://pypi.org/project/twine/1.10.0/ is now out!

**Comment by brainwane** [comment]
And @mplanchard I hope you'll be at [the PyCon sprints](https://us.pycon.org/2018/community/sprints/) in May to collaborate with other packaging/distribution folks!
