### ISSUE TITLE
pypi.python.org shutting down

### ISSUE THREAD

**Issue by LHolst** [pypiserver/pypiserver#205]
> New PyPI launched, legacy PyPI shutting down April 30

https://pythoninsider.blogspot.de/2018/04/new-pypi-launched-legacy-pypi-shutting.html

`fallback-url` should use _https://pypi.org/simple after_ April

**Comment by blade2005** [comment]
I think this a great step forward and allows for more sane practices as we can drop support of XML-RPC in the future.

**Comment by mplanchard** [comment]
Agreed! Please feel free to open a PR if you have the time before I get to this.

**Comment by brainwane** [comment]
I hope https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi helps!

**Comment by mplanchard** [comment]
Definitely! The changes are easy enough to make. I just got married last week and am leaving for my honeymoon on Friday, though, so I've been even more pressed than usual. I might have some time Thursday night to get this in.

If I don't get it in before Friday, there's no chance it's getting done before the end of the month.
