### ISSUE TITLE
pypiserver docker file is missing manifest

### ISSUE THREAD

**Issue by renich** [pypiserver/pypiserver#211]
I get hte following error while pulling:

```
renich@introdesk ~ $ docker pull pypiserver/pypiserver
Using default tag: latest
Error response from daemon: manifest for pypiserver/pypiserver:latest not found
```

**Comment by renich** [comment]
Very kind of you to answer. Thanks!

**Comment by renich** [comment]
Any progress on this?

**Comment by mplanchard** [comment]
The new version's a big update, so it's taking a fair bit of time 😅 

If having a Docker image in the repo tagged with `latest` is something you'd find valuable, though, I can make a "featureless" release just to get the automated system kicked off to create an image for the current version. Would that be helpful?

**Comment by mplanchard** [comment]
I went ahead and released [`v1.2.3`](https://github.com/pypiserver/pypiserver/releases/tag/v1.2.3) to ensure we've got some official tags in the Docker [repo](https://hub.docker.com/r/pypiserver/pypiserver/tags/). Unfortunately, the automated builds seem to be currently [broken](https://github.com/docker/hub-feedback/issues/1592), but I was able to get them built manually.

I can confirm that I can now pull the `latest` image, as expected 😁

```
(py37) ➜  pypiserver git:(master) docker pull pypiserver/pypiserver:latest
latest: Pulling from pypiserver/pypiserver
8e3ba11ec2a2: Pull complete
4001a9c615cb: Pull complete
e826c7cf5577: Pull complete
c953aede322e: Pull complete
f3f93fbe5386: Pull complete
6b35a0fa972f: Pull complete
b5f8b76f20f3: Pull complete
9f763e6fac10: Pull complete
Digest: sha256:36147142de1a3b02484b600239696c2fd2628f7ad1dccbb713bf171292e3156e
Status: Downloaded newer image for pypiserver/pypiserver:latest
(py37) ➜  pypiserver git:(master) docker pull pypiserver/pypiserver
Using default tag: latest
latest: Pulling from pypiserver/pypiserver
Digest: sha256:36147142de1a3b02484b600239696c2fd2628f7ad1dccbb713bf171292e3156e
Status: Image is up to date for pypiserver/pypiserver:latest
```

I'm going to go ahead and close this.

**Comment by renich** [comment]
Dude, you rock! Thanks a lot. I'll try and see if I can put this into kubernetes through helm. 

Thanks again!

**Comment by mplanchard** [comment]
No problem! If all works out well with Kubernetes, please feel free to open a PR or an issue with the manifest settings that worked for you, and we’ll get them added to the docs.
