### ISSUE TITLE
ReadOnly permissions

### ISSUE THREAD

**Issue by 80kk** [pypiserver/pypiserver#223]
Is it possible to have PyPi server with Apache based authentication with two users, one with full access and other one with RO access?

**Comment by mplanchard** [comment]
At the moment, differential permissions based on users are not possible. However, we are working towards a more flexible architecture that should allow us to implement these kinds of features much more easily in the future

**Comment by lukasz-madon** [comment]
@mplanchard ant update on this? Seems like a very common use case. I want only my CI/CD server and admin to write. The rest can only download libraries.

**Comment by mplanchard** [comment]
I'm still working on a "version 2" in my spare time, but it's got to compete with lots of other priorities, i.e. work that pays the bills and family. 

@lukasz-madon would allowing unauthenticated downloads and restricting other operations work for your use-case? Or is it essential that the download permission be scoped to a particular user?

If this is something that people have more of an interest in, I'm happy to reopen this issue to get more feedback and consider patching the current version prior to releasing a new version with a more fully baked permissions model, but I suspect that opening up downloads while restricting other operations satisfies a majority of users' needs. Happy to be proven wrong, though!

**Comment by lukasz-madon** [comment]
> allowing unauthenticated download

Not really. Basically, I'd like to block Data Scientist push something to pypi by accident and breaking other people code.

>  compete with lots of other priorities, i.e. work that pays the bills and family.

As we all do :) Thanks for your effort.

**Comment by mplanchard** [comment]
I think one of the major things I'd like to add in the next version is proper RBAC, so you can e.g. have a DataScientist role that you assign to users, granting them permissions to do x, y, and z authenticated actions. Please let me know if you have any particular wants for such a system so I can get them into the design!

**Comment by vEpiphyte** [comment]
@mplanchard Have you had any further thoughts on this? I'm looking at a similar issue as @lukasz-madon mentioned.

**Comment by mplanchard** [comment]
No, I haven't been able to get to this yet, and it probably won't make it into the initial implementation of the next major version.

Depending on how you have your infra set up, it might be possible to restrict POST requests via nginx using the same htpasswd file that you use for pypiserver: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by FelixSchwarz** [comment]
Just wanted to mention that I would like to see this functionality as well and if I understood this correctly, restricting reads is not yet implemented.

My use case is similar to what was written above:

- I want to provide a private pypi server for my organization. The packages hosted there contain proprietary code so only authenticated users should see/download the packages.
- Additionally most accounts should have read-only access to mitigate the effects of compromised accounts/prevent developers from pushing directly to production.

Currently I tend to create a custom `auther` function that can also check bottle's request. In case of a `GET` request I would then also check a second password file.

**Comment by dee-me-tree-or-love** [comment]
Hello @FelixSchwarz! Thanks a lot for the reminder on this issue. I'm feeling quite guilty for not finding the time to properly solve this issue yet, so my apologies for the long waiting time. Seeing my current available time, I can't promise quick delivery of this feature (although there are some truly great PRs already open - for which massive kudos 🙌) but this idea is certainly on a high priority list. 

A current naive workaround (the way I currently do it for my needs) - is to run the `pypi-server` behind a private VPN. Like this only people with VPN access will be able to connect to the server for downloading, and only specific users can be given the write access using the usual methods. I know that it's more of a "shifting the problem" approach and there are limitations, but I hope it could somehow help you out nonetheless. This at least bought me the time until an embedded auth solution. Please let me know, I'll be curious to hear your reflections if this works out.
