### ISSUE TITLE
pip search to fallback url

### ISSUE THREAD

**Issue by TalLoss** [pypiserver/pypiserver#231]
Hello!
Ive started to look around your pypiserver, and one of my tests was to check pip search to the fallback url, which apparently didn't really work for me.
I'm pretty sure it's because the function 'handle_rpc()' in _app.py, which isn't configured correctly, it only searches on the local packages a and not redirecting to the fallback url like the pip install (which pip sends a new GET request with the url given back from the pypiserver):
`for p in packages():`
I might be wrong, but will br happy for an answer!

**Comment by mplanchard** [comment]
Thanks for bringing this up!

Currently, fallback does not work with search. See [this comment](https://github.com/pypiserver/pypiserver/issues/181#issuecomment-335872710) for details as to why.

I did a little bit of work exploring the idea of making downstream requests for fallbacks, which was tracked [here](https://github.com/pypiserver/pypiserver/issues/177) but never got fully tested or merged.

If you specify `--extra-index-url` in your pip config, search should fallback as expected. I understand that may not be ideal for every use case though.

**Comment by mplanchard** [comment]
Also, apologies for the late response. I wasn't on the computer much over the holidays 😅
