### ISSUE TITLE
mirror with bandersnatch and run pypiserver on that

### ISSUE THREAD

**Issue by GreatBahram** [pypiserver/pypiserver#234]
HI there,
I want to mirror some packages from pypi with bandersnatch' whitelist plugin and serves that as a private pypi server with pypiserver? is that possible? is there any problem? and users also be able to publish their private packages on that server? is that OK?

Thanks

**Comment by mplanchard** [comment]
Hey, sorry for the slow response here. I was busy over the holidays and then got _rather_ distracted with normal workaday stuff.

Were you able to do this? I honestly have never tried to mirror pypiserver with bandersnatch, and I don't know enough about bandersnatch to say for certain whether it should work or not.

**Comment by mplanchard** [comment]
Good to know. Thanks for the update!

**Comment by GreatBahram** [comment]
You're welcome!

**Comment by ews-ffarella** [comment]
> Hiya! Well, I've tested that with bandersnatch. There were some problems with bandersnatch. First and foremost, when you're using it as whitelist it does not resolve package's dependencies so that means you cannot do that with bandersnatch. For future users(who want to do this like me), I've done that with devpi. Although devpi does not let you mirror all versions of a package you can overcome to that issue easily compare to adding dependency resolver to bandersnatch.
> 
> Thanks

@GreatBahram Hi! Did you manage to get this setup run with docker compose?
