### ISSUE TITLE
Copied packages not showing up in Index of packages

### ISSUE THREAD

**Issue by shaneberry** [pypiserver/pypiserver#236]
Hi,

I am trying out pypiserver and have copied a package into the packages folder, but the package does not show up in Index of packages.  I am wondering if there is any format the package needs to be in.  I copied the folder which has the __init__.py file and all of the python files in it.  The folder structure looks like this:

~/packages/requests/
         __init__.py
         api.py
        etc...

Is that what it is expecting?

**Comment by mplanchard** [comment]
Not quite! You’ll need to have your package built as either a wheel or a source distribution before uploading it to your pypiserver. This link should get you started: https://packaging.python.org/tutorials/packaging-projects/

Let me know if you run into any problems!

**Comment by mplanchard** [comment]
Closing this for now. Please feel free to reopen if you have more questions
