### ISSUE TITLE
CRLF injection via new line characters in URI

### ISSUE THREAD

**Issue by samwcyo** [pypiserver/pypiserver#237]
**Summary**
pypiserver doesn't escape new line characters when redirecting users. I'm not too sure if this is only in the default installation, or that if users used a redirect functionality it would additionally be vulnerable.

**Steps to Reproduce**
1. Download pypiserver and host a default installation
2. Open http://pypiserver/%0d%0aSet-Cookie:malicious=1;
3. Observe cookie being set

**Impact**
Create arbitrary HTTP responses, set malicious cookies, potential for XSS depending on implementation (i.e. location header doesn't redirect to a valid host and therefore displays whatever content is available)

**Comment by mplanchard** [comment]
Thanks for the report! I'll look into this and try to get it fixed ASAP.

**Comment by mplanchard** [comment]
#238 I think should resolve this. At least it fixes it when running locally for me, on python 2 and 3. Could you take a look and see what you think, if you've got time?

**Comment by Prathapdhanapal** [comment]
Pixel quality

**Comment by Prathapdhanapal** [comment]
Pixel quality
