### ISSUE TITLE
What is the easiest way to setup HTTPS with pypi server?

### ISSUE THREAD

**Issue by jopollack** [pypiserver/pypiserver#247]
I've encountered issues with my personal install of pypiserver not supporting https, and the --trusted-host flag being unsatisfactory as a workaround, so I'm curious what the lowest bar to entry method of enabling HTTPS with pypiserver is, as I see no instructions of any kind in the documentation about how to go about this.

Should a different WSGI server be utilized? If so, how is certificate information provided for these plugins? For example, if I ran pypiserver with cherrypy using this command:
```
pypi-server -p 8080 --server cherrypy ~/packages
``` 
how do I provide my private key/certificate information to the script? Is there a flag I'm not seeing, or a configuration file that needs to be edited?

Or is it the case that there is no out of the box method of handling HTTPS with pypiserver itself, and I need to setup something with Apache or Nginx?

**Comment by mplanchard** [comment]
The easiest, safest, and fastest way is probably to stick it behind nginx with a certificate from LetsEncrypt.

[Here](https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/) is a blog post on setting up nginx to use LetsEncrypt.

We currently have no plans to implement native SSL support in pypiserver. We would prefer to leave that to the professionals. 

The CLI for pypiserver doesn't support passing arbitrary commandline arguments to the server passed to the `--server` command, but depending on the server, you may be able to set a configuration file or something similar. All that being said, the best solution is still probably to run your pypiserver instance as an HTTP service on a local port and use `nginx` or another webserver as a reverse proxy to it. That process is described in our docs [here](https://github.com/pypiserver/pypiserver#behind-a-reverse-proxy)

**Comment by Helveg** [comment]
Another easy way is to use a `VirtualHost` directive in Apache with `mod_wsgi`. You can configure your vhost to use SSL like you normally would in Apache, a process for which extensive documentation and tools are freely available.

## Minimal addition to your VirtualHost directive

```
    WSGIScriptAlias / /var/www/wsgi/pypi.wsgi
    <Directory ~/packages>
        Require all granted
    </Directory>
```

The `WSGIScriptAlias` allows you to specify a "mount" location for you pypiserver, here the `/` root of the VirtualHost was used but you could also for example locate it under `/package-index`.

## Minimal WSGI script
```
import pypiserver
PACKAGES = '~/packages'
application = pypiserver.app(root=PACKAGES, redirect_to_fallback=False)
```

**Comment by mplanchard** [comment]
@Helveg we don't have a lot in the docs for running w/apache, so if you'd be willing to toss this into the README somewhere, I'd gladly take a docs contribution!

**Comment by Helveg** [comment]
I checked the README and it all seems to be there, it just doesn't mention HTTPS.

**Comment by Helveg** [comment]
I gave it a go here https://github.com/pypiserver/pypiserver/pull/289 but I couldn't really find a good place for mentioning these things.

**Comment by mplanchard** [comment]
We've had some really great discussion and contributions here. Thanks everybody! I'm going to close this for now just for organizational purposes. Feel free to reopen if there's more discussion to be had.
