### ISSUE TITLE
Why is it useless after setting a password?

### ISSUE THREAD

**Issue by ILTShade** [pypiserver/pypiserver#252]
I run this for a passed-procteced
```
pypi-server -p 8080 -P htpasswd.txt -a update,download ./packages &
```

but when I try to download some package using
```
pip download sh --no-cache-dir --extra-index-url http://localhost:8080 -d .
```

I get this
```
Looking in indexes: https://pypi.org/simple, http://localhost:8080
Collecting sh
127.0.0.1 - - [06/May/2019 20:28:11] "GET /sh/ HTTP/1.1" 303 0
127.0.0.1 - - [06/May/2019 20:28:11] "GET /simple/sh/ HTTP/1.1" 200 309
  Downloading https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl
  Saved ./sh-1.12.14-py2.py3-none-any.whl
Successfully downloaded sh
127.0.0.1 - - [06/May/2019 20:28:20] "GET /pip/ HTTP/1.1" 303 0
127.0.0.1 - - [06/May/2019 20:28:20] "GET /simple/pip/ HTTP/1.1" 303 0
```

why does this happen?

**Comment by mplanchard** [comment]
You specified `--extra-index-url`, which means pip should look in your local index _as well as_ the normal PyPI index. And if you read your error output, you can see that you are in fact downloading `sh` from `https://files.pythonhosted.org/packages`, which is not your local server.

If you want to only download from your local server, you'll need to specify `--index` instead.
