### ISSUE TITLE
Is it a expected behaviour that it requires restart of wsgi server after adding a package locally?

### ISSUE THREAD

**Issue by smekkley** [pypiserver/pypiserver#260]
I'm using uwsgi, but every time I add a package, I need to restart the server in order for a client to install or find the new package. Reload doesn't work as well.

**Comment by smekkley** [comment]
I've set cache_control=1, then the issue was solved. Sorry for making the unnecessary issue.

**Comment by mplanchard** [comment]
No worries! Glad to see you resolved it :)
