### ISSUE TITLE
Binary wheels on Linux?

### ISSUE THREAD

**Issue by dan-stromberg** [pypiserver/pypiserver#262]
Pypi does not accept the upload of binary wheels for Linux.

Does pypi-server allow Linux binary wheels?  I'm hoping it does.

**Comment by mplanchard** [comment]
I don't see why we wouldn't, unless either a) pip won't download them or b) setuptools/twine won't upload them, we conform to the [simple repository interface fro PEP-503](https://www.python.org/dev/peps/pep-0503/).

If you try it and it doesn't work, please let me know!

**Comment by mplanchard** [comment]
Closing for now. Please feel free to re-open if needed
