### ISSUE TITLE
Docker blocks request on MacOS

### ISSUE THREAD

**Issue by ayiis** [pypiserver/pypiserver#263]
Hi, thanks for your work. 

I use the latest docker version by

```
docker run pypiserver/pypiserver:latest
```

It works fine on Centos, but it's easily got blocked when processing requests on MacOS. 
At:

```code
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
  File "/usr/lib/python2.7/socket.py", line 480, in readline
KeyboardInterrupt
```

However, it seems something to do with `simple_server` and related to an issue of Python itself at https://bugs.python.org/issue21878.

I guess most people don't use this project on MacOS, I'd like to post more info if you need.

Systeminfo:

```code

Darwin xxxxxx 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin

Docker version 18.09.2, build 6247962

Python 3.7.4

```

**Comment by mplanchard** [comment]
Thanks for the report! I have run this on MacOS, but not "officially," like to serve packages externally. Luckily, that means I can dig in!

Could you explain to me the best way of replicating the error? Does this happen on every request?

**Comment by ayiis** [comment]
Yes, I'm glad to. It rarely happens. It's working good and quick behind the `curl` or `wget` command all the time.

Here's how I replicate the issue: 

```
1. Start the pypi container
2. Browse the pypi server http://127.0.0.1:8080/ with Chrome
3. Now, this request is blocked, and the later coming requests are all waiting.
```

It has a 50% chance to block the request, and it often happens after I reload the page in the Chrome. If it's not, stop the container and try it again with the above step.

**Comment by mplanchard** [comment]
Sorry it's taken me a while to get back to you on this! I'm having trouble reproducing locally. 

I ran the pypiserver container, opened up the website in Chrome and Firefox, and then started a loop of `while true; do curl localhost:8080/simple/; sleep 0.5; done`. I then went back to the browsers and started pressing cmd+r over and over to refresh the page.

I was only able to get 200 responses the entire time :(

**Comment by ayiis** [comment]
That's great it works fine on yours.

I just pulled the latest `pypi` image and tried again, and the exactly same thing happened, it still blocks my request for some reason. However, since I am the only one issue this situation, I suppose there may be something wrong within my MacOS.

I closed this issue, if I dug deeper I'll be back with an update.

Thanks for your time. Have a nice day.

**Comment by mplanchard** [comment]
No worries! Please feel free to re-open if needed, and I'm happy to dig in further if you get more info.
