### ISSUE TITLE
Docker Image 1.3.0 Dockerfile minor configuration change

### ISSUE THREAD

**Issue by mkolb-navican** [pypiserver/pypiserver#264]
The apk py2-pip package installation should be with the base container otherwise the command "pypi-server -U /data/packages" will error:

pypi-server -U /data/packages
Traceback (most recent call last):
  File "/usr/bin/pypi-server", line 11, in <module>
    load_entry_point('pypiserver==1.3.0', 'console_scripts', 'pypi-server')()
  File "build/bdist.linux-x86_64/egg/pypiserver/__main__.py", line 273, in main
  File "build/bdist.linux-x86_64/egg/pypiserver/manage.py", line 11, in <module>
ImportError: No module named pip

Also, I recommend using an absolute path for the Dockerfile CMD ["/data/packages"]

Do you have detailed documentation using the --log-* options at the command line? I have been appending the Dockerfile to add logging. 

I did add "apk update" and "apk upgrade" to my Dockerfile to update the Alpine instance packages when the container is built. Are there version dependencies that adding these commands would break the application?

**Comment by mplanchard** [comment]
Thanks for the report. I will try to dig into this soon. 

Regarding logging, the default I believe goes to stdout with the level of `WARNING`. If you run without specifying a log file but upping the verbosity some number of `-v` arguments, do you get better output?

**Comment by mplanchard** [comment]
I believe that e074cd7 fixes the docker issue! It should be out on the `unstable` channel here shortly for testing, or you can build it yourself.

Regarding your question I missed when I originally read this issue:

> I did add "apk update" and "apk upgrade" to my Dockerfile to update the Alpine instance packages when the container is built. Are there version dependencies that adding these commands would break the application?

I believe you should be fine. The only system libraries we install are python ones, and there's no reason that updating those should affect the application that I know of.
