### ISSUE TITLE
remove_pkg action does not remove all instances the package

### ISSUE THREAD

**Issue by esciara** [pypiserver/pypiserver#268]
If a package at a certain version has been uploaded in several formats, only one is removed when performing the `remove_pkg` action. Hence when trying to upload the package again for instance, the upload will fail.

For instance, packages could be uploaded in `*.tar.gz` and in `.whl` formats, as in my case:
```
my_package-0.1.0-py3-none-any.whl
my_package-0.1.0.tar.gz
```
The code causing the issue is:
https://github.com/pypiserver/pypiserver/blob/91a5ebd8b11bc0fef42614dcf539b2910239c8af/pypiserver/_app.py#L134-L141
One can see that the `for` loop exits once the first package is found.

Corrective code in line with the writing style could be:
```
        found = []
        for pkg in find_packages(packages()):
            if pkg.pkgname == name and pkg.version == version:
                found.append(pkg)
        if not found :
            raise HTTPError(404, "%s (%s) not found" % (name, version))
        for pkg in find_packages(packages()):
            os.unlink(pkg.fn)
```
I would offer a PR, but don't want to do that without associating a test with it. And I unfortunately won't have the time to ding into the test code to find out how to do it... :disappointed:

**Comment by mplanchard** [comment]
Yep, that makes sense. Thanks for the report! I'll try to get to this this week[end].

**Comment by ruifpedro** [comment]
Heya @mplanchard, do you have any idea of when this fix will be available in docker images (excluding unstable)?

**Comment by mplanchard** [comment]
@ruifpedro sorry for the delay. Q4 is a terrible time for OSS commitments for me. I'll be pushing to try to get a new release out sometime either before the new year or shortly thereafter

**Comment by ruifpedro** [comment]
> @ruifpedro sorry for the delay. Q4 is a terrible time for OSS commitments for me. I'll be pushing to try to get a new release out sometime either before the new year or shortly thereafter

No worries. Totally fine with that time scale, thanks for your commitment.
I hope you'll have a very good Christmas and a Happy New year!

**Comment by mplanchard** [comment]
This fix is now available in v1.3.2, both in PyPI and as a Docker image 🎉

**Comment by LordEvron** [comment]
@mplanchard  This bug seems to be still present in v1.3.2 running on latest docker image.
curl --form ":action=remove_pkg" --form "name=$mypackage" --form "version=0.0.0" $PYPIURL 
Still remove only the tar.gz file and not the .whl.

**Comment by chancez** [comment]
Yeah im seeing wheels getting left behind.

**Comment by chancez** [comment]
https://github.com/pypiserver/pypiserver/blob/df300de33d2ffe01f218396813433f23001dd76b/pypiserver/pkg_helpers.py#L65-L69

The wheel regex doesn't seem to match our wheels names, probably because of the newlines.

**Comment by mplanchard** [comment]
good to know, thanks! Could y'all open a new issue so I don't lose track of it? Going to be a minute though. I'm in Austin, and we're having a bit of a rough week here

**Comment by chancez** [comment]
Can we just re-open this one since it didn't get fixed in the original PR?

**Comment by mplanchard** [comment]
Not if you want me to remember to fix it

**Comment by mplanchard** [comment]
I'm also not entirely convinced that it's the regex fwiw:

```
import re
>>> wheel_file_re = re.compile(
    r"""^(?P<namever>(?P<name>.+?)-(?P<ver>\d.*?))
    ((-(?P<build>\d.*?))?-(?P<pyver>.+?)-(?P<abi>.+?)-(?P<plat>.+?)
    \.whl|\.dist-info)$""",
    re.VERBOSE,
)
>>> wheel_file_re.match("foo-bar-1.0-py3-none-any.whl")
<re.Match object; span=(0, 28), match='foo-bar-1.0-py3-none-any.whl'>
>>> wheel_file_re.fullmatch("foo-bar-1.0-py3-none-any.whl")
<re.Match object; span=(0, 28), match='foo-bar-1.0-py3-none-any.whl'>
```

but I'd welcome a PR to fix w/tests that show it's broken. Otherwise, like I said, please open a new issue specifying what files you aren't seeing removed, with as much context as you can give me to help me figure out why the current tests aren't catching your issue.
