### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by Hedgehogues** [pypiserver/pypiserver#274]
Hey. I really liked pypi-server. It is awesome enough to just run and easy to use. Thank you for your work.

But I still have a question, can I just as easily configure the roles on the pypi-server to access specific resources. It seems that I can do this with reverse-proxy, but I'm not sure if pip can just interact with it. Tell me, is there any easy way to do this? Is it possible to do this with https://github.com/pypiserver/pypiserver-passlib? I did not find a description, so I do not fully understand why this lib is needed

**Comment by mplanchard** [comment]
Glad it's mostly working for you!

> can I just as easily configure the roles on the pypi-server to access specific resources

Do you mean for specific packages?

Having passlib installed allows you to specify that certain actions (download, upload, etc.) be restricted unless someone has the username/password (supplied via HTTP basic auth). This works well with pip and twine. The passlib dependency is just to read a "passlib" file, which just a way of storing hashed passwords (https://passlib.readthedocs.io/en/stable/).

We don't currently have the ability to specify different authorization schemes for specific packages, though.
