### ISSUE TITLE
Not found any packages

### ISSUE THREAD

**Issue by Hedgehogues** [pypiserver/pypiserver#297]
I do next things 

```pip install --extra-index-url http://1.2.3.4:8081/ grader_v2_storage --trusted-host 1.2.3.4```

After that, I get 

```
ERROR: Could not find a version that satisfies the requirement grader_v2_storage==1.6.11 (from versions: none)
ERROR: No matching distribution found for grader_v2_storage==1.6.11

```

I have next config on ~/.pip/pip.conf:

```
[global]
index-url = http://login:pass\\word@1.2.3.4:8081/simple/
trusted-host = pypi.python.org
               pypi.org
               1.2.3.4
```

Notice: I have login as **login** and password as **pass\\word** (warning)!

If I remove config above, I can login with handle login and password:

```
Looking in indexes: https://pypi.org/simple, http://1.2.3.4:8081/simple/
User for 1.2.3.4:8081: login
Password: 

```

**Comment by Hedgehogues** [comment]
How I fix it?

**Comment by Hedgehogues** [comment]
This is problem with password

**Comment by mplanchard** [comment]
Glad you figured it out! Thanks for following up & closing the issue
