### ISSUE TITLE
Setting password for docker image

### ISSUE THREAD

**Issue by CatsNipYummy** [pypiserver/pypiserver#305]
How do I set the username and password while running pypiserver docker image? Or is there a default username and password set? I am not able to upload using twine cause I am not sure about the username and password.

**Comment by olefemmy** [comment]
You might need to use docker volume and reference it in the `pypiserver` command on startup like ` -P /data/auth/.htpasswd -v -a update,download /data/packages`. In other words, you should have mounted `/data/auth` to a local folder where you have created a `.htpasswd` file containing the user/password credentials. I don't think the permission is correct within the docker image though, which I have advised in a ticket now.

**Comment by CatsNipYummy** [comment]
Thanks. Referencing issue here #306

**Comment by mplanchard** [comment]
Going to go ahead and close this. Feel free to respond if you need any more help or would like to reopen the issue 👍
