### ISSUE TITLE
Question: Any suggestions for running on Windows as service

### ISSUE THREAD

**Issue by kodaman2** [pypiserver/pypiserver#313]
Any suggestions on running on windows as a service? I don't seem to find any info online. Is there such solution other than a full blown apache server?

My needs are very small, and works great with the quickstart commands.

**Comment by kodaman2** [comment]
Nevermind just tried NSSM https://nssm.cc/ for anyone looking for how to do it:

create a batch file such as start_pypiserver.bat, I made the bat inside my Packages folder but it can be anywhere:

start_pypiserver.bat:
```
pypi-server -p 8080 ~/packages & 
```

Download nssm, and place in Program Directories, and also in environment PATH.

```
nssm install pypiserver
```

This will launch a small window, on path browse to the bat. Then change service name to pypiserver.

Lastly start the service:

```
nssm start pypiserver
```

**Comment by mplanchard** [comment]
Super glad you found a way to do this, and thanks for following up with implementation details! Feel free, if you feel like it, to open a PR to add these instructions to the README for anyone else working on windows. Otherwise I'll make a note to include this in the next update

**Comment by kodaman2** [comment]
@mplanchard No problem, I'll submit PR here in the next few days. That will definitely help windows users for sure.
