### ISSUE TITLE
Deprecation warning due to invalid escape sequences 

### ISSUE THREAD

**Issue by tirkarthi** [pypiserver/pypiserver#315]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -v example | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./pypiserver/core.py:137: DeprecationWarning: invalid escape sequence \.
  "\.win-amd64-py[23]\.\d\..*|\.win32-py[23]\.\d\..*|\.egg)$",
```

**Comment by mplanchard** [comment]
Thanks for raising this issue! I'll get these updated for the next version 👍. Also happy to accept a patch if you've got the time.
