### ISSUE TITLE
different credentials for upload / download

### ISSUE THREAD

**Issue by dm-intropic** [pypiserver/pypiserver#318]
More a question than issue - it is possible to have one set of credentials for uploading packages to the server, and different credentials for downloading? 
Would like to restrict who can upload to a smaller set than who can download, but unsure if this functionality is here / on the roadmap.

**Comment by mplanchard** [comment]
Unfortunately it's not currently possible to have different credentials per authenticated user. This is something we're interested in adding eventually, but for now, if you need this functionality, you might want to check out [an alternative](https://github.com/pypiserver/pypiserver#similar-projects) server.

**Comment by mplanchard** [comment]
Closing this for now. Please feel free to reopen if you have further questions.
