### ISSUE TITLE
Running pypiserver from script

### ISSUE THREAD

**Issue by g3n35i5** [pypiserver/pypiserver#331]
PyPiServer works perfectly, thank you very much for the great work! I would like to know if it is intended that the server can also be started from a script, something like

```python
from pypiserver import server

config = {
  "port": 4242,
}

# ...
server.run(**config)
```

**Comment by dee-me-tree-or-love** [comment]
yes, that can work too. What you would need to do is:   
```python
# my_pypiserver.py
from pypiserver import app
from pypiserver import bottle

app = app(port=4242) # and possible to provide other overrides, for example different root folder: root=['./local_packages']
bottle.run(app)
```
and then run it with python: 
```bash
$ python my_pypiserver.py

Bottle v0.13-dev server starting up (using WSGIRefServer())...
Listening on http://127.0.0.1:8080/
Hit Ctrl-C to quit.
``` 

You can also use this approach to run it with [`gunicorn`](https://gunicorn.org/) or other servers, e.g. `gunicorn -w 4 my_pypiserver:app`

**Comment by g3n35i5** [comment]
Awesome, thank you very much! I'll close this issue.

**Comment by g3n35i5** [comment]
I know, it's a little late to ask but I didn't get a chance to try your answer before... Unfortunately, the configuration attributes are not taken over by me (and not by you either, you set port 4242 and bottle uses the default port 8080.

So for all of you who want to use this: Even in the implementation the call botte.run is done like this:
https://github.com/pypiserver/pypiserver/blob/c668b1814a0a50ca056af5e02f3469546ecf81e1/pypiserver/__main__.py#L94-L99

So if you want to change port and host, you have to change the following in your answer:
```python
app = app(root=['/foo/bar']) # All other configurations must go here
bottle.run(app, host="0.0.0.0", port=4242) # Host and port must go here
```
