### ISSUE TITLE
How to make the server read-only?

### ISSUE THREAD

**Issue by 1ace** [pypiserver/pypiserver#337]
Hi! I'm currently evaluating ways to provide in-house packages and this looks like a good option, but having any of the employees able to upload packages doesn't sound very good (a mistake happens easily).

I would like `pypiserver` to serve the contents but disallow uploads, and we'll simply `scp` the packages we want to upload (and reload/restart the server if that's necessary). The documentation doesn't seem to mention anything like that, is it at all possible?

**Comment by mplanchard** [comment]
Sure, yeah, I think so.

If you want to allow unauthenticated downloads and restrict uploads, you can run with `pypi-server --authenticate update <path>`. If you don't provide a password file, there are no users for it to auth against, and so there's no way to successfully authenticate for updates.

If you need to restrict downloads to authenticated users while _also_ disallowing uploads, unfortunately that's not supported currently. We've got some efforts underway to modernize some of the internals of pypiserver, so it's possible this will be added in the future, but I can't give you any sort of definite timeline.

**Comment by mplanchard** [comment]
I'm going to close this for now. Feel free to reopen if you have more questions.
