### ISSUE TITLE
damaged docker image pypiserver/pypiserver:v.1.4.0

### ISSUE THREAD

**Issue by jacek-jablonski** [pypiserver/pypiserver#340]
Hello,
image v1.4.0 on docker hub image seems to be damaged.

```
docker pull pypiserver/pypiserver:v1.4.0

v1.4.0: Pulling from pypiserver/pypiserver
df20fa9351a1: Already exists
36b3adc4ff6f: Already exists
7eaf559fa1af: Already exists
ff42851d39f6: Already exists
8ba142e34a43: Already exists
553aa7897213: Pulling fs layer
3cb2dcdb6061: Pulling fs layer
92eefad90d68: Pulling fs layer
a5f30824aae7: Waiting
error pulling image configuration: unknown blob
```

Please check if everything is ok with this docker image.

**Comment by mplanchard** [comment]
Thanks very much for the report! I'm not sure what happened there. I went ahead and rebuilt the images for the `v1.4.0` and `latest` tags and confirmed I'm able to pull them down successfully. Let me know if that resolves things for you.

**Comment by jacek-jablonski** [comment]
It's now ok. Thank you!
