### ISSUE TITLE
v1.4.x changes not merged into master

### ISSUE THREAD

**Issue by elfjes** [pypiserver/pypiserver#345]
There are currently a number of commits in the v1.4.x branch that are not merged to master. Is this intentional? Shouldn't we merge those into master? PR #344 is currently targets the v1.4.x but I'd much rather just have it all into master.

**Comment by mplanchard** [comment]
We've added tings into master that are not v1.4.x compatible, b/c they break compatibility with Python <3.6, so fixes being merged into that branch are appropriate. We will need to merge those fixes back into master. I just haven't gotten around to it yet.

**Comment by mplanchard** [comment]
Merged in the v1.4.x changes, including #344.

**Comment by elfjes** [comment]
> We've added tings into master that are not v1.4.x compatible, b/c they break compatibility with Python <3.6, so fixes being merged into that branch are appropriate. We will need to merge those fixes back into master. I just haven't gotten around to it yet.

Cool, no worries, I didn't want to rush you or anything. Was just wondering :)

**Comment by mplanchard** [comment]
Oh yeah, it's no problem, and you're completely right! I was being lazy, and if we had waited longer to merge them in, it would've been more and more of a pain. Thanks for the reminder!
