### ISSUE TITLE
Improve Docker tests

### ISSUE THREAD

**Issue by mplanchard** [pypiserver/pypiserver#346]
Right now we have some pretty minimal tests for the docker container in `bin/test-docker.sh`.

Recent issues (#343, #341, #340, #330) show that quite a few people are using the dockerfile to run pypiserver, so we should increase the test coverage to include authenticated cases, cases with a variety of arguments, etc.

We can continue to add cases into the bash script, or we can pull this stuff into regular pytest tests that set up the docker container via a test fixture.

**Comment by elfjes** [comment]
Running them in pytest sounds like a good idea to me. Ideally I guess we may want to run the same tests from `test_server.py` against a running docker container.  However, the tests in `test_server.py` already take quite a long time. Is there a way to speed up those tests?

**Comment by mplanchard** [comment]
I believe this should be resolved by #359
