### ISSUE TITLE
Official Docker image support for ARM?

### ISSUE THREAD

**Issue by SiqingYu** [pypiserver/pypiserver#364]
Hi Pythonistas, I want to port our private PyPI server Docker container to ARM. But I found the official build on Docker Hub only supports amd64. Is there any plan for ARM support?

Reference:
https://hub.docker.com/r/pypiserver/pypiserver

**Comment by mplanchard** [comment]
This isn't something I'd thought about, but we can play around with the docker build at some point to see if we can manage it.

**Comment by SiqingYu** [comment]
I have succeeded in building the Docker image on an ARM machine. The Dockerfile works well because the Python Alpine image has already supported ARM.

**Comment by mplanchard** [comment]
Out of curiosity, what's the benefit here? Do you see better performance on ARM, is it cheaper to run, etc.? I don't mind providing an official ARM build, but I'd be curious to know if there's any difference you've noticed in your environment

**Comment by SiqingYu** [comment]
@mplanchard Because our company deploys commercial Python software on-prem, so we need to ship it with a pypiserver container. It happens that some of our customers are migrating to ARM servers.

I guess this might be one fallout from the trade war. Now big enterprises in my country are eager to migrate to the ARM platform. You can easily guess who the ARM platform's maker is.

**Comment by mplanchard** [comment]
Ah, that makes sense. We can definitely get this added. I'll add it as part of the v2.0 release, but since that'll be a while, I can also backport it to the current v1.4 branch when it's done, so that it's not blocked on getting all the other v2.0 work done.

**Comment by caniko** [comment]
Hello, everyone, and @dee-me-tree-or-love!

Would be more than happy to help out with this.

Design solution:
- Every release should trigger an automatic docker build
- We should update the version with compatibility `~=` and not pinning `==` as we do currently
- Docker builds should be for every architecture x86, arm64, and risc-v

We would have to start storing the DockerHub secrets on the repository.

Anything I missed that would be of interest? I would like to do come to an agreement as soon as possible!

Thank you!

**Comment by dee-me-tree-or-love** [comment]
Hello everyone, thanks a lot for all your inputs and interest! To make sure we have a single place for all references regarding this goal, let's continue the discussion in #468 ❤️ 

Thanks to the work of @cbwchuck in #553, we should be much closer to supporting this ✌️
There are some more fixes pending on the `main` branch which might still delay the availability of the `arm` images, the repo's slowly heading in that direction. Please bear with me for a little bit.

Sorry for all the waiting and huge thanks for all the help ❤️

**Comment by dee-me-tree-or-love** [comment]
Closing to avoid duplicate threads, let's continue all discussions in #468.
