### ISSUE TITLE
AttributeError: 'Configuration' object has no attribute 'welcome_msg'

### ISSUE THREAD

**Issue by pault28** [pypiserver/pypiserver#376]
I have just tried the docker image `pypiserver/pypiserver:v1.4.2` and it errors with:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pypiserver/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.8/site-packages/pypiserver/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.8/site-packages/pypiserver/_app.py", line 112, in root
    msg = config.welcome_msg + "\n"
AttributeError: 'Configuration' object has no attribute 'welcome_msg'
```
How is this new attribute pass via the command line? 

This is an attempt to take advantage of the fixes in https://github.com/pypiserver/pypiserver/pull/371.

**Comment by pault28** [comment]
Works fine on `pypiserver/pypiserver:unstable`. Maybe `pypiserver/pypiserver:v1.4.2` is not fully ready for use yet.

**Comment by mplanchard** [comment]
Yep, I haven't backported the changes currently in master (corresponding to the `unstable`) docker tag to the 1.4 branch yet. We're having issue getting consistent internet and power in Austin this week, but I hope to backport as much as I can soon!
