### ISSUE TITLE
Add Healtcheck endpoint

### ISSUE THREAD

**Issue by rodrigo-fss** [pypiserver/pypiserver#387]
It would be great if pypiserver had a health check endpoint.
something like /health, answering 200 OK
so it could be possible to serve this application using something like ECS or k8

**Comment by dee-me-tree-or-love** [comment]
@rodrigo-fss I think it's a great idea. I will try try pick it up in the coming days. Otherwise feel free to create a MR if you'd like to add it yourself ;)

@mplanchard I think that's something small we could easily incorporate? What do you think?
