### ISSUE TITLE
pload failed (403): Forbidden

### ISSUE THREAD

**Issue by lslstudy** [pypiserver/pypiserver#389]
upload customized pip package failed using following command:
`python setup.py sdist upload -r local`, 
and ~/.pypirc file configuration like: 
`[distutils]
index-servers =
    local

[local]
repository: http://127.0.0.1:8000
username:
password:`

**Comment by Koldar** [comment]
Hi, just leaving another possibility of why it occurs. In my scenario I mistakenly set `--password` to an empty string. Setting `--password` to an empty file or to a file without the specified user will produce the same error
