### ISSUE TITLE
Can't run with Podman : 'exec user process caused: exec format error'

### ISSUE THREAD

**Issue by azataiot** [pypiserver/pypiserver#394]
CMD:
``` 
 podman run -p 6000:8080 -v ~/packages:/data/packages pypiserver/pypiserver:latest
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by eriol** [comment]
@azataiot what version of podman are you using? It worked for me using podman 3.0.1.

**Comment by metalsp0rk** [comment]
This error is caused by an architecture mismatch.  `exec format error` indicates that the container image you downloaded is not compiled for the architecture of the machine you are running on.  

pypiserver is only built for amd64 on dockerhub as of writing.

**Comment by azataiot** [comment]
> This error is caused by an architecture mismatch.  `exec format error` indicates that the container image you downloaded is not compiled for the architecture of the machine you are running on.  
> 
> 
> 
> pypiserver is only built for amd64 on dockerhub as of writing.

Thanks, this solved my problem. I tried to change the install script little bit and rebuild the docker image and now it worked on Raspberry Pi(arm64)
