### ISSUE TITLE
After I have upgraded pip to 22.0, pypiserver started to occur; HTML doctype missing or incorrect. Expected  <!DOCTYPE html>.

### ISSUE THREAD

**Issue by lidyum** [pypiserver/pypiserver#412]
After I have upgraded pip to 22.0, pypiserver started to occur the following error. (I use python 3.8)
```
ValueError: HTML doctype missing or incorrect. Expected <!DOCTYPE html>.

If you believe this error to be incorrect, try passing the command line option --use-deprecated=html5lib and please leave a comment on the pip issue at https://github.com/pypa/pip/issues/10825.
```

**Comment by sharmankin** [comment]
i get same issue to. As temporary solvation i comment 
```
    def handle_starttag(self, tag: str, attrs: List[Tuple[str, Optional[str]]]) -> None:
        #if not self._seen_decl:
        #    self._raise_error()
```
in 408 line of venv/lib/python3.9/site-packages/pip/_internal/index/collector.py in pip

**Comment by mv1005** [comment]
I can confirm same issue here. Reason seems to be a change in the HTML parsing code used by pip (see pypa/pip#10825).

If I correctly understand the discussion, pip now rejects HTML documents which are not valid HTML5. According to the specs (see PEP 503: https://www.python.org/dev/peps/pep-0503/#specification) this is a valid expectation.

**Comment by domdfcoding** [comment]
I have just spun up a `pypiserver` instance and it appears that the generated pages omit the doctype declaration entirely. It's present on the welcome page, but not on `/simple` or the project pages. It's an easy fix, though.

**Comment by mv1005** [comment]
Thanks for that instant fix :slightly_smiling_face:.

**Comment by duardos** [comment]
After a fix is released for this, does anyone have any idea of how should we update our indexes? Will it be needed to download all our packages again to regenrate it, or is there another way? I'm not too knowledgeable on how pip works.

**Comment by mv1005** [comment]
Maybe I just don't get the point... but I am not sure what exactly you are referring to.
* Updating the local indexes served by your pypiserver?
* Updating python packages on client side?
* Something different?

**Comment by duardos** [comment]
> Maybe I just don't get the point... but I am not sure what exactly you are referring to.
> 
>     * Updating the local indexes served by your pypiserver?
> 
>     * Updating python packages on client side?
> 
>     * Something different?

First option! I mean, even after upgrading pypiserver (after a fix is provided), the old HTML documents without <!DOCTYPE html> will remain in my indexes, won't they? Or does pypiserver take care of that?

**Comment by mv1005** [comment]
The HTML files are created on the fly by your pypi server based on the package files it has stored. This happens at the time you request a package via `pip`. So, updating the server should immediately provide you with properly formatted HTML pages.

Am 31. Januar 2022 09:07:51 MEZ schrieb duardos ***@***.***>:

**Comment by lidyum** [comment]
I think problem has been resolved because pip has been updated to 22.0.1 ??

[pip changelog](https://pip.pypa.io/en/stable/news/)

**change logs 22.0.1 (2022-01-30)**
Bug Fixes

- Accept lowercase <!doctype html> on index pages. (#10844)

- Properly handle links parsed by html5lib, when using `--use-deprecated=html5lib. (#10846)

**Comment by mv1005** [comment]
Pip 22.0.1 does not "fix" the breaking change introduced by version 22.0.0. It still rejects HTML which does not contain `DOCTYPE` at all. However, version 22.0.1 does also except a lower case `doctype`, which 22.0.0 did not.

In contrast to that, pip 22.0.2 reverts the original breaking change and issues just a warning instead of rejecting pages which do not comply with the HTML5 specs.

**Comment by domdfcoding** [comment]
As far as I understand, the latest version of pip (22.0.3) will no longer error-out if it detects invalid HTML. Instead it will only emit a warning.

**Comment by Seluj78** [comment]
Just a heads up, this message dissapears when upgrading from `22.0.2` to the latest version.

For anyone that still might encounter this issue, I recommend updating your `pypiserver` to the latest version and also update `pip` to the latest version (`pip install --upgrade pip`)
