### ISSUE TITLE
Preparing new `pypiserver` release

### ISSUE THREAD

**Issue by dee-me-tree-or-love** [pypiserver/pypiserver#419]
> TO BE ELABORATED. 

# Purpose

Hey everyone, I wanted to make a public strategy for the upcoming release collected in this issue as, unfortunately, it is taking me longer than I have anticipated. I'm getting there but would like to apologize for the delays. I'm promising to get it up and running. 

Here I would like to make a draft roadmap of things I'm working on to get it ready.   
Any help and suggestions on this are very welcome!

## Timeline

- [x] Receive the release credentials and access to DockerHub and Pypi
- [x] Prepare a low-labor release process (in progress)
  - [x] Setup the release candidate preparation flow (#417)
  - [x] Setup the release CI/CD pipeline (#423)
- [x] Get a new release published
- [ ] Document updated release process

**Comment by dee-me-tree-or-love** [comment]
#417 is ready for review. All suggestions and comments are welcome, I aim to get it merged and create a new release candidate by the end of the week :)

**Comment by SuperSandro2000** [comment]
The PEP 503 warning will no longer check for DOCTYPE in the next release https://github.com/pypa/pip/pull/10906

**Comment by dee-me-tree-or-love** [comment]
Hi all! A new release has been finally pushed :) My huge apologies for the delay and all the bumps on the way there.  

https://github.com/pypiserver/pypiserver/releases/tag/v1.5.0

It was my first release in this repo, so do not hesitate to contact/open a new issue in case you find anything strange! 
Many thanks for all the patience.
