### ISSUE TITLE
Allow users to customize the health check endpoint

### ISSUE THREAD

**Issue by Mason-Lin** [pypiserver/pypiserver#441]
Hope to allow users to customize the health check endpoint
For example /health, /healthz, /health/live, /api/health, /action/health

I checked whether there is a conventional health endpoint and found that /healthz is relatively common usage
, but each team may still define some different paths.

I tried adding `--health-endpoint` to RunConfig, but I found that there was no `config` when creating the endpoint
I finally chose to use environment variables `HEALTH_ENDPOINT`.

I create a MR for this change #442 

Related Issue and MR
https://github.com/pypiserver/pypiserver/issues/387
https://github.com/pypiserver/pypiserver/pull/396

Related articles I refer to
https://stackoverflow.com/questions/43380939/where-does-the-convention-of-using-healthz-for-application-health-checks-come-f
https://testfully.io/blog/api-health-check-monitoring/
https://docs.openshift.com/container-platform/4.11/applications/application-health.html

**Comment by dee-me-tree-or-love** [comment]
Solved in https://github.com/pypiserver/pypiserver/pull/442 👍✨
