### ISSUE TITLE
Can´t download package 

### ISSUE THREAD

**Issue by m3xw3ll** [pypiserver/pypiserver#467]
Hello, 

I try to run pypiserver with docker on a Linux server. 
I have a very easy test package, here is the directory structure:
```
.
└── my_packs/
    ├── package_1/
    │   └── __init__.py
    └── setup.py
```

the `__init__.py` contains:
```
def say_hello():
    print('hello world')
```

I run following command to build the package `python setup.py sdist`
After that I start the docker container with 
`sudo docker run -p 80:8080 -v /data/my_packs:/data/packages pypiserver/pypiserver:latest`

If i visit `http://<servername>:80` I can see the welcome to pypiserver! website serving 1 package. So I guess I started the container the right way. 

Now on the client side I want to download this package. I tried following pip install:
`pip install --extra-index-url http://<myserver>:80/simple/ package_1 --proxy <proxy>:<port> --trusted-host <myserver>`

But I always get an HTTPConeectionPool Error

My pip.ini looks like that:
```
[global]
extra-index-url = http://<myserver>:80

[install]
trusted-host = <myserver>
```

Any help is appreciated.

**Comment by m3xw3ll** [comment]
I solved the problem. I built the package with `python setup.py bdist_wheel --universal` and ran `pip install .`
After that I was able to download the package as desribed above.

**Comment by dee-me-tree-or-love** [comment]
Great! Thanks a lot for the note on the solution @m3xw3ll ! 👍
