### ISSUE TITLE
Set up Dependabot for `dev` dependencies

### ISSUE THREAD

**Issue by dee-me-tree-or-love** [pypiserver/pypiserver#475]
# What

Currently, dependencies like `black`, used for style checking of `pypiserver`'s code, are not pinned. This results in silent version updates in the CI pipelines, which may disrupt the integration for changes (PRs) unrelated to styling guidelines etc. I believe it would be beneficial to have a consistent policy for updates of such dependencies so that the style adaptations happen explicitly and do not affect other work unexpectedly.

## Current status of Dependabot

[Dependabot](https://github.com/dependabot) is used for the `pypiserver` but does not seem to trace all the dependencies of this project. In my opinion, it would be important to:

- [ ] Validate the configuration of Dependabot
- [ ] Refine the rules of Dependanbot
- [ ] Make sure that the dev dependencies are addressed by Dependabot

## From discussion

> @cclauss, I fully understand the point and agree with the not-falling-behind idea! :) Given that there will be more changes throughout the year (seeing the releases of `22.X.Y`), and expecting that eventually we'll reach `24.X.Y` in a year from now, I'd personally vote for using a tool like [`dependabot`](https://github.com/dependabot) to maintain the up-to-date versioning in a contained fashion, preventing CI issues on unrelated changes 🤔 So in that case, we'd get notified of the recent updates in a separate PR, allowing us to adapt the code base accordingly when necessary, keeping the other work less impacted. But I am not 100% certain how to set this up yet and I will probably make it a milestone for the next maintenance steps and hope to tackle it quickly :) What would be your opinion on this? 

_Originally posted by @dee-me-tree-or-love in https://github.com/pypiserver/pypiserver/issues/474#issuecomment-1413634304_

**Comment by ghinks** [comment]
I was going to take a quick look at this as it is within my capabilities. Just a note, when I tried to fork this project it did seem to do so. Are there some forking restrictions?

**Comment by dee-me-tree-or-love** [comment]
Hi @ghinks! Thanks a lot for reacting to this issue, this would be a very valuable addition and that's amazing if you'd like to pick it up :) There are no restrictions to forking, so feel welcome to start. 

When you're ready to submit a PR, there are also no special processes. Just FYI, when reviewing I'll also check for any possible GitHub Action adjustments and enable them to run on your PR too, but that's all easy. Feel at ease to work on it the way you like and if you have any further questions, feel free to reach out (here, in the PR, or Zulip)! 

Thanks again for your willingness to contribute, let me know if I can help you out somehow 👍

**Comment by ghinks** [comment]
Very happy to see if the trailing slash in 491 did the trick on discovery of test.pip somehow.

**Comment by dee-me-tree-or-love** [comment]
Oh, thanks a lot @ghinks 👍 And special thanks for noticing the @cclauss's PR, I must have missed it, so thanks to you both for addressing this! I will review #493 and the related PRs right now.
