### ISSUE TITLE
Docker is (no longer 🎉) moving to paid organisations (but still 💭)

### ISSUE THREAD

**Issue by mplanchard** [pypiserver/pypiserver#482]
See https://blog.alexellis.io/docker-is-deleting-open-source-images/

and https://news.ycombinator.com/item?id=35166317

We use an organization account for pypiserver, so we’ll need to move. GitHub container registry seems like a reasonable choice. 

We could probably qualify for docker’s open source program, but it seems like applications are taking over a year to process at the moment.

**Comment by dee-me-tree-or-love** [comment]
Hey @mplanchard! Thanks for the heads-up! I've also seen an email passing through, I'm planning to take action sometime this weekend/end of next week 🙌

**Comment by dee-me-tree-or-love** [comment]
> GitHub container registry seems like a reasonable choice.

True! However, there's one catch in GHCR allowing `500MB of Package storage` for free tiers. 🤔 I think that's a good move for the time being with the sunset of the Docker Hub's plan getting quite close. Still, we'd need to double-check and calculate our usage forecasts and then consider the support policy for older packages if we want to stay within the limits. I'll still be looking into it. 👍 I think I'll start working on it this week.

➕ I've checked some other container registries but couldn't find another good and affordable option yet. 
❤️ Any community ideas are very welcome!

**Comment by dee-me-tree-or-love** [comment]
Also, this is a great thought! 

> We could probably qualify for docker’s open source program, but it seems like applications are taking over a year to process at the moment.

From the [Docker's FAQ](https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf?utm_campaign=2023-03-14-operational-team-discontinued-ft&utm_medium=email&utm_source=marketo&mkt_tok=NzkwLVNTQi0zNzUAAAGKf9y4rq3mGT-UVZeUiHvpkl8_aKOgwtOyxcvRl8SB_IzRnup5AmB-Yt9uS5xN72gKMy1CVOcjJ5xmk8nrttU5zKjGAZaDZi_xj8cPTyulh28I1x9QTes): 

> _For new **users interested in joining DSOS from a previous Free Team organization, we will defer any organization suspension** or deletion while the DSOS application is under review._

Besides, to put the timeline to this, the suspension deadline (AFAIU) [is](https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf?utm_campaign=2023-03-14-operational-team-discontinued-ft&utm_medium=email&utm_source=marketo&mkt_tok=NzkwLVNTQi0zNzUAAAGKf9y4rq3mGT-UVZeUiHvpkl8_aKOgwtOyxcvRl8SB_IzRnup5AmB-Yt9uS5xN72gKMy1CVOcjJ5xmk8nrttU5zKjGAZaDZi_xj8cPTyulh28I1x9QTes): "_as of **April 13, 2023**_".

CC @mplanchard

**Comment by dee-me-tree-or-love** [comment]
Btw, this appears to be a related discussion area on the Docker side: https://github.com/docker/hub-feedback/issues/2314

**Comment by mplanchard** [comment]
Hi, sorry for my absence on this. We’re in the process of moving states, which is a lot of work, and it’s been a wildly busy few weeks at work. 

Luckily, it looks like Docker has reversed course: https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/

Regardless though I agree with your conclusions: we should apply for Docker’s open source program just in case they change their minds again, and pursue GHCR as a backup. Luckily there is now less urgency!

**Comment by dee-me-tree-or-love** [comment]
Hey @mplanchard, thanks a lot for the note! Indeed I have also received the news from Docker and that allowed me to get a bit of extra time to breathe as well - it's indeed great to have the urgency off our shoulders 😅 I Hope your moving went well, I can totally imagine it must be quite an effort! 

I'm going to continue on this issue indeed as proposed above but in a slightly more relaxed tempo :) I might need to ask for some help from you for double checking as I'll be preparing all the [checklists for the DSOS program ](https://www.docker.com/community/open-source/application/) but I'll keep you posted 🙌

**Comment by dee-me-tree-or-love** [comment]
For future reference, consider this discussion about cleaning up the untagged images https://github.com/orgs/community/discussions/26716
