### ISSUE TITLE
Setuptools is replacing distutils warning

### ISSUE THREAD

**Issue by dee-me-tree-or-love** [pypiserver/pypiserver#488]
> > Hi @dee-me-tree-or-love, this the command I run , and the output. 
> > C:\inetpub\pypiserver>pypi-server update -v -d c:\inetpub\pypiserver\packages
> > C:\Program Files\Python310\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
> > warnings.warn("Setuptools is replacing distutils.")
> > checking 0 packages for newer version
> > 
> >Thank you.
>
> _Originally posted by @Tonyttlab in https://github.com/pypiserver/pypiserver/issues/487#issuecomment-1538192242_
     
The warning is worth investigating separately.

**Comment by stefan6419846** [comment]
There seem to be two places where *pypiserver* is importing the deprecated *distutils* package:

* https://github.com/pypiserver/pypiserver/blob/3f520cdc1827d3d1c10e1edfa7b4e9969aff5a0c/pypiserver/config.py#L46 Implemented in https://github.com/pypa/setuptools/blob/6083e18f4afc40316c0112134c205c336afbcdfd/setuptools/_distutils/util.py#L340-L353 and https://github.com/pypa/setuptools/blob/6083e18f4afc40316c0112134c205c336afbcdfd/setuptools/_distutils/tests/test_util.py#L177-L185
* https://github.com/pypiserver/pypiserver/blob/3f520cdc1827d3d1c10e1edfa7b4e9969aff5a0c/pypiserver/manage.py#L8 Only used for detecting legacy *pip*, id est *pip* before version 10.0: https://github.com/pypiserver/pypiserver/blob/3f520cdc1827d3d1c10e1edfa7b4e9969aff5a0c/pypiserver/manage.py#L117 *pip* 10.0.0 has been released on 2018-04-14: https://pip.pypa.io/en/stable/news/#v10-0-0

**Comment by dee-me-tree-or-love** [comment]
@stefan6419846 cc @Tonyttlab I believe this was fixed in #539 :v: 
I'll close this issue, but feel free to re-open if this still seems relevant.
