### ISSUE TITLE
Missing dependency: pip

### ISSUE THREAD

**Issue by pawamoy** [pypiserver/pypiserver#490]
pypiserver imports pip, but does not declare it as a dependency, resulting in a `ModuleNotFoundError` in some cases:

```
Traceback (most recent call last):
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/pypiserver/__main__.py", line 143, in main
    from pypiserver.manage import update_all_packages
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/pypiserver/manage.py", line 13, in <module>
    import pip
ModuleNotFoundError: No module named 'pip'
```

I understand that pip is very often available in a given environment, though it's not always the case. I can send a PR if needed :slightly_smiling_face:

**Comment by dee-me-tree-or-love** [comment]
Hey @pawamoy! Wow, thanks a lot for catching this! :) This is awesome that you've spotted this 😊 🌟  I've been seeing this implicit dependency (and even a sub-process use, iirc 👀) for a while but didn't get to investigate yet, and this is just great. So yes please, if you could open a PR with a fix, I'd really appreciate 🙂
