### ISSUE TITLE
README.md TOC Links not working on github

### ISSUE THREAD

**Issue by ghinks** [pypiserver/pypiserver#513]
The readme.md links in the newer markdown file are not taking the users to the correct ( or any section ) in the markdown file when viewed on the pypiserver homepage. If the README.md file is clicked upon and opened directly in viewing mode the links do work correctly.

After investigation it has been found that on the [main page](https://github.com/pypiserver/pypiserver) TOC links to header links do not work. They do work on the [README.md preview](https://github.com/pypiserver/pypiserver/blob/master/README.md). 

I will raise a PR changing the headers from links to regular headings i.e.

an example of the required change is:

```markdown
## [Quickstart Installation and Usage](#pypiserver)
```
to

```markdown
## Quickstart Installation and Usage
```

I did test systematically but I did so in the preview page.

**Comment by dee-me-tree-or-love** [comment]
Oh good catch @ghinks! Thanks for noticing, TOCs and MD are always a bit tricky :) For the time being, I've checked that GH itself correctly sees the TOC: 

> <img width="328" alt="image" src="https://github.com/pypiserver/pypiserver/assets/12134172/dab3edbb-6622-47d2-8769-94ea27f90eea">

So hopefully this can help to bypass the challenge for a while. But indeed thanks for noticing this again! ⭐ 
Do you need some help fixing this?

**Comment by ghinks** [comment]
Thank you I made the changes I thought should get [get this to work in my fork](https://github.com/ghinks/pypiserver) and set that branch as the primary and it still did not link. So I'm scratching my head now.

**Comment by dee-me-tree-or-love** [comment]
> Thank you I made the changes I thought should get [get this to work in my fork](https://github.com/ghinks/pypiserver) and set that branch as the primary and it still did not link. So I'm scratching my head now.

Oh hey, no worries @ghinks, we can scratch both our heads on it 😄 If you'd like you can open a draft PR from your fork and I can think along! Interesting 🕵️

**Comment by ghinks** [comment]
I'll open a draft PR. It could be a number of things.

**Comment by dee-me-tree-or-love** [comment]
Awesome, thanks for opening the PR @ghinks! I will try to check it out in my free time coming week 👍
