### ISSUE TITLE
Provide hash in the link for local packages

### ISSUE THREAD

**Issue by Ivoz** [pypiserver/pypiserver#53]
pip 1.5 and greater would like secure links by default, which by implementation means the link provides a hash of the package in the url. This provides some form of verification of correct file download at least.

You can see some of the [api docs at warehouse](http://warehouse.readthedocs.org/en/latest/api-reference/legacy/#get--simple--project--) how this is done.

It would be great for pypiserver's links to provide this for pip; I believe this would mean you no longer have to pass `--allow-insecure`.

**Comment by ankostis** [comment]
I may have gotten this wrong, but why is a DB needed for pip's secure-links?
Isn't it enough for pypiserver to check that the requested hash matches the hosted or fail-through package's hash?

**Comment by ror6ax** [comment]
Well, remaking hash every time it's requested is a bit overhead, right?
I'll finish this in nearest future.

**Comment by ankostis** [comment]
My feeling is that current CPUs have more than enough juice for such numerical tasks.
Of course this may not apply for embedded ones.

**Comment by ankostis** [comment]
Note that the hashes contained on the link-fragments served by PyPI are NOT used by `pip`: https://pip.pypa.io/en/latest/reference/pip_install/#hashes-from-pypi

**Comment by Ivoz** [comment]
:thumb: nice work ankostis
