### ISSUE TITLE
DEPRECATION: The HTML index page being used is not a proper HTML 5 document. (from docker pypiserver:v2.1.1)

### ISSUE THREAD

**Issue by nicc777** [pypiserver/pypiserver#580]
Hi

I use the docker version for local development and testing of packages.

When I use pip to install packages from the local repo, I get the following message:

```text
DEPRECATION: The HTML index page being used (http://REDACTED/simple/REDACTED/) is not a proper HTML 5 document. This is in violation of PEP 503 which requires these pages to be well-formed HTML 5 documents. Please reach out to the owners of this index page, and ask them to update this index page to a valid HTML 5 document. pip 22.2 will enforce this behaviour change. Discussion can be found at https://github.com/pypa/pip/issues/10825
```

I am currently using pip `22.0.2`, so I fear I will face failure to be able to use this is in my near future.

Will it be possible to change the HTML pages to proper HTML 5 formatted documents?

Thanks!

**Comment by dee-me-tree-or-love** [comment]
Thanks for noticing and raising this issue @nicc777! 🌟 
I'll try to book some time for this shortly! I'll need to double check how we do the HTML rendering and update the format 👍 

----

> [!NOTE]
> I'll try prioritise this but I'm a little busy these days with different wrap-ups, so if I'm not reacting here promptly, please don't hesitate to ping me. 🙏

**Comment by nicc777** [comment]
Thanks @dee-me-tree-or-love - I saw some places where the HTML is hard coded, so if I have a chance I can also create a PR.

**Comment by dee-me-tree-or-love** [comment]
> Thanks @dee-me-tree-or-love - I saw some places where the HTML is hard coded, so if I have a chance I can also create a PR.

Awesome, if you do find the time to do so, that would be amazing, I would really appreciate 🙏  but don't feel obliged otherwise!
