### ISSUE TITLE
question: can i set pypi server as a proxy ?

### ISSUE THREAD

**Issue by johndou-and-friends** [pypiserver/pypiserver#587]
hi can i set pypi server as a normal pypi server and a proxy server?

For example I want to publish 1 package on my self-hosted pypi server 

and when i request for that specific package server give it back to me but when i request for a package that is not on server locally server automatically get data from original pypi.org server (as a proxy)

**Comment by pawamoy** [comment]
Yes, see the "fallback" option :)

**Comment by johndou-and-friends** [comment]
> Yes, see the "fallback" option :) It's enabled by default so you actually don't have to do anything for it to work.

and also another question how can i change default index html page?

**Comment by pawamoy** [comment]
This I don't know. You should open a new issue with this question (after making sure no one asked that already), so that other users may find it :)
