### ISSUE TITLE
Incompatibility with any packages requiring Python3.9+

### ISSUE THREAD

**Issue by daniel-brenot** [pypiserver/pypiserver#594]
When i tried to use this at work, I ran into the issue that this doesn't work when you have any version of xarray made after 2023 as a dependency, since it requires python 3.9 or greater.

I'm working on a pull request now that I would ideally like merged as it solves this problem, however I understand if there are worries over backwards compatibility.

**Comment by oz123** [comment]
Pypiserver works fine with current versions of Python.

**Comment by pawamoy** [comment]
> I'm working on a pull request now that I would ideally like merged as it solves this problem, however I understand if there are worries over backwards compatibility.

It's usually better if you can actually describe what "doesn't work" and provide a minimal reproducible example first (MRE), before sending a PR, so that maintainers can confirm the issue. Then the technical solution can be discussed, and then only, a PR sent :slightly_smiling_face:

**Comment by daniel-brenot** [comment]
Im no longer working at the workplace where this was an issue so you may feel free to ignore this.

From what i was remembering, i couldn't install xarray on this because the version was too old. I believe it was a weird use case that frankly was just solved by using the python base image instead. Not sure why they were using this one. Have a great day.

**Comment by dee-me-tree-or-love** [comment]
Thanks a lot for the update @daniel-brenot 👍 
We'll keep this issue the loop in case it shows up again. 
Hopefully it was indeed just an unfortunate set of circumstances 🤞 :)
