### ISSUE TITLE
Please update vendored `bottle`

### ISSUE THREAD

**Issue by mgorny** [pypiserver/pypiserver#604]
[bottle](https://pypi.org/project/bottle/) 0.13.1 has been released recently, with support for Python 3.13. Unfortunately, from a quick look it introduced also some API changes.

**Comment by dee-me-tree-or-love** [comment]
Hey @mgorny, thanks a lot for reporting the issue! Indeed, making bottle a more proper dependency is very much on the list!
I'll try to address this in the coming month, but all help is very welcome 🙏 ⭐
