### ISSUE TITLE
support protected downloads and listings

### ISSUE THREAD

**Issue by petri** [pypiserver/pypiserver#65]
This would make pypiserver useful for serving a private (proprietary) package repository.

**Comment by petri** [comment]
Looks like this would be simple to add. I can make a pull request with the following command-line enhancements:
 1. add new option ```-s | --secure = download | upload | both``` that also requires giving ```-P```
 2. modify behavior of ```-P``` option slightly so that using it also requires giving  ```-s | --secure```

That ok?

**Comment by petri** [comment]
Ended up implementing separate auth for listings as well, using the ```-a | --authenticate``` option, with comma-separated values as python ```getopt```does not support multiple values... Pull request coming.

**Comment by ankostis** [comment]
PR#66 merged.

@petri is this ready to close?

**Comment by petri** [comment]
Fine with me.
