### ISSUE TITLE
Release v1.1.7

### ISSUE THREAD

**Issue by ankostis** [pypiserver/pypiserver#68]
@schmir, @ror6ax and @dingus9:
I believe it is time to make the 1st public release under the new ownership scheme.

- The PR's marked for inclusion are marked with milestone=v1.1.7.
- I'm hopping to start merging during the weekend.
- Arbitrarily set release-date on 25-January.
- @schmir i will need you to give access to my pypi-account (named also `ankostis`) for uploading released packages.
- @dingus9 you have to add yourself into the watchers of this project (it is not done automatically).

**Comment by schmir** [comment]
Kostis Anagnostopoulos <notifications@github.com> writes:

> - @schmir i will need you to give access to my pypi-account (named
> also `ankostis`) for uploading released packages.

@ankostis you now have owner rights on pypi

**Comment by ror6ax** [comment]
Hi guys, I wasn't around for a while, sorry.
I'm ok with the release. Anything hold us from doing it?

**Comment by ankostis** [comment]
Procrastination, sorry :-)

**Comment by aspyatkin** [comment]
Hi, would the new release be available on PyPI soon?

P.S. I suppose there is a typo in issue name

**Comment by ankostis** [comment]
@aspyatkin @1.1.7-beta.0 is ready, and actually we are looking for beta-testers since this is the 1st release under the new maintainer-team.

Would you mind trying it with this command (assuming `git` is in your path): 

```
pip install git+git://github.com/pypiserver/pypiserver.git@1.1.7-beta.0
```

Just make sure that you have uninstall any older installation.

**Comment by aspyatkin** [comment]
Oh, that's great! I will certainly try the new version.

**Comment by ankostis** [comment]
@aspyatkin I would propose to use the repo with `--extra-index-url <url>` instead of `` --index-url <url>     ``, or set that permanently into you ``~/.pip/pip.conf``, since this repo is not a proper-replacement for the main *pypi*, (i.e. for mispelled packages, see to #38).

I'm planning to change that part in the documentation prior to release.

**Comment by aspyatkin** [comment]
@ankostis OK, I will take it into consideration. Thank you!

**Comment by ankostis** [comment]
@schmir Just did a RC release: 
- https://pypi.python.org/pypi/pypiserver/1.1.7-rc.1
- https://github.com/pypiserver/pypiserver/releases/tag/1.1.7-rc.1

Would need a `--pre` option to install it.

**Comment by HenrikOssipoff** [comment]
Just wanted to pitch in with feedback; thank you for the 1.1.7 rc release. We've been running it on our internal pypi repository and all issues we've been having with pip 6.x have vanished with this release. Much appreciated -- keep up the amazing work!

**Comment by ankostis** [comment]
@HenrikOssipoff  Thank you very much for your feedback.

Therefore... Released!
