### ISSUE TITLE
Does not work in Windows?

### ISSUE THREAD

**Issue by cpaulik** [pypiserver/pypiserver#76]
I've set up pypiserver 1.1.6 on Windows7 using python 2.7.9 and pip 6.0.8.

```http://localhost:8080/simple/``` lists my package without problems but
```pip install -i http://localhost:8080/simple pygrids``` says:

```
Collecting pygrids
  DEPRECATION: Failed to find 'pygrids' at http://localhost:8080/simple/pygrids/. It is suggested to upgrade your index to support
 normalized names as the name in /simple/{name}.
  Cannot fetch index base URL http://localhost:8080/simple/
  Could not find any downloads that satisfy the requirement pygrids
  No distributions at all found for pygrids
```

The different version of the pygrids package are:

```
pygrids-0.1.tar.gz
pygrids-0.2.tar.gz
pygrids-0.2.1.tar.gz
```

Same setup works on Ubuntu 14.04

**Comment by ankostis** [comment]
Could it be related to #38?
If yes, then the question is why it works in ubuntu...

**Comment by ankostis** [comment]
@cpaulik  may you try the option `--extra-index-url` instead of `-i`? 
Do you still get the same behavior?

**Comment by cpaulik** [comment]
Hi,

The exact url of the package is http://localhost:8080/simple/pygrids/ there I see the tar.gz files listed.

Using the ```--extra-index-url``` leads to a slightly different error:

```
Collecting pygrids
  Could not find any downloads that satisfy the requirement pygrids
  No distributions at all found for pygrids
```

**Comment by ankostis** [comment]
I'm sorry to bother you again, but could you provide me with 2 more things:

1. The print-out of the command: 

      pip install pygrids -v --extra-index-url=http://localhost:8080/simple/ --retries=1

2. The contents of the pypiserver's repo folder as seen with windows-explorer (i'm looking specifically for the case of the ``pygrids`` folder & filenames).

**Comment by cpaulik** [comment]
No problem, thanks for taking the time to look into this.

```
D:\winpython\WinPython-64bit-2.7.9.2\python-2.7.9.amd64>pip install pygrids -v --extra-index-url=http://localhost:8080/simple/ --r
etries=1
Collecting pygrids
  Getting page https://pypi.python.org/simple/pygrids/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/pygrids/ HTTP/1.1" 404 28063
  Could not fetch URL https://pypi.python.org/simple/pygrids/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/pygrids/ when looking for download links for pygrids
  URLs to search for versions for pygrids:
  * https://pypi.python.org/simple/pygrids/
  * http://localhost:8080/simple/pygrids/
  Getting page https://pypi.python.org/simple/pygrids/
  "GET /simple/pygrids/ HTTP/1.1" 404 28063
  Could not fetch URL https://pypi.python.org/simple/pygrids/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/pygrids/ when looking for download links for pygrids
  Getting page http://localhost:8080/simple/pygrids/
  Starting new HTTP connection (1): proxy.ipf.tuwien.ac.at
  "GET http://localhost:8080/simple/pygrids/ HTTP/1.1" 504 1131
  Could not fetch URL http://localhost:8080/simple/pygrids/: 504 Server Error: Gateway Time-out
  Will skip URL http://localhost:8080/simple/pygrids/ when looking for download links for pygrids
  Could not find any downloads that satisfy the requirement pygrids
  Cleaning up...
  No distributions at all found for pygrids
  Exception information:
  Traceback (most recent call last):
    File "D:\winpython\WinPython-64bit-2.7.9.2\python-2.7.9.amd64\lib\site-packages\pip\basecommand.py", line 232, in main
      status = self.run(options, args)
    File "D:\winpython\WinPython-64bit-2.7.9.2\python-2.7.9.amd64\lib\site-packages\pip\commands\install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "D:\winpython\WinPython-64bit-2.7.9.2\python-2.7.9.amd64\lib\site-packages\pip\req\req_set.py", line 333, in prepare_file
s
      upgrade=self.upgrade,
    File "D:\winpython\WinPython-64bit-2.7.9.2\python-2.7.9.amd64\lib\site-packages\pip\index.py", line 397, in find_requirement
      'No distributions at all found for %s' % req
  DistributionNotFound: No distributions at all found for pygrids
```

I started the server with the command:

```
D:\winpython\WinPython-64bit-2.7.9.2>pypi-server -p 8080 d:\piptest
This is pypiserver 1.1.6 serving 'd:\\piptest' on http://0.0.0.0:8080

Bottle v0.11.6 server starting up (using AutoServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

127.0.0.1 - - [20/Feb/2015 10:24:53] "GET /simple/pygrids/ HTTP/1.1" 200 170
127.0.0.1 - - [20/Feb/2015 10:24:54] "GET /simple/pygrids/ HTTP/1.1" 200 170
127.0.0.1 - - [20/Feb/2015 10:24:55] "GET /simple/pygrids/ HTTP/1.1" 200 170
127.0.0.1 - - [20/Feb/2015 11:52:36] "GET / HTTP/1.1" 200 782
127.0.0.1 - - [20/Feb/2015 11:52:38] "GET /simple/ HTTP/1.1" 200 102
127.0.0.1 - - [20/Feb/2015 11:52:40] "GET /simple/pygrids/ HTTP/1.1" 200 170
```

Content of piptest folder

![image](https://cloud.githubusercontent.com/assets/380927/6284999/3738ae8c-b8f7-11e4-97d1-175f69a58f62.png)

Browser view of ```localhost:8080/simple/pygrids```

![image](https://cloud.githubusercontent.com/assets/380927/6285024/6e4a295a-b8f7-11e4-9c38-41e335341365.png)

**Comment by ankostis** [comment]
It is the following line that shouldn't be there:
```Starting new HTTP connection (1): proxy.ipf.tuwien.ac.at```
Is it possible to disable this proxy somehow?

Additionally, when you say that it works in Ubuntu, what exactly do you mean? 
Running the `pypiserver` in it, `pip install`, or both?

**Comment by cpaulik** [comment]
Thank you and sorry for the confusion. It works if I disable the proxy. 

Why does it not work with the proxy? Can we configure the proxy to also work with pip? Because disabling it is not a long term option.

On ubuntu the server and installing works but I guess ubuntu ignores the proxy for localhost better than windows.

**Comment by ankostis** [comment]
It is supposed to work fine with proxies.

The most probable explanation is that it fails because you have installed *pypiserver* it on your localhost - a proxy can only handle regular Domain-Names.  Unfortunately just from the `502` response we cannot be sure whether that is the problem.

Maybe the following may help you resolve this issue:
- http://stackoverflow.com/questions/13559377/curl-bypass-proxy-for-localhost
- http://stackoverflow.com/questions/14149422/using-pip-behind-a-proxy

**Comment by ankostis** [comment]
By the way, a viable solution in your case would be to have *pypiserver* use your proxy, downstream.This will be my 1st priority after releasing 1.1.7 at the end of this week (see   #19).

**Comment by cpaulik** [comment]
Thanks for the additional information. I'll try to install it on the server where it was supposed to go after successful testing and configure our proxy to work with it.

**Comment by ankostis** [comment]
Assuming it was not a bug.
