### ISSUE TITLE
Allow Search with Pip

### ISSUE THREAD

**Issue by psaavedra** [pypiserver/pypiserver#80]
This patch hacks the code in order to allow *pip search PKG*. For example:

    pip search  --index http://pypi.intenet.com:8080/search/ MyDjango

I wonder if you are interested on this and if this patch is wellcome for your side.

<pre>
--- /root/_app.py	2015-03-12 11:16:23.000000000 +0000
+++ /usr/local/lib/python2.7/dist-packages/pypiserver/_app.py	2015-03-12 12:26:29.000000000 +0000
@@ -6,6 +6,7 @@
 import mimetypes
 import logging
 import pkg_resources
+import xml.dom.minidom
 
 try:
     from io import BytesIO
@@ -24,6 +25,48 @@
 log = logging.getLogger('pypiserver.http')
 packages = None
 
+XMLRPC_RESPONSE_SKELETON='''<?xml version='1.0'?>
+<methodResponse>
+<params>
+<param>
+<value>
+%(objects)s
+</value>
+</param>
+</params>
+</methodResponse>'''
+
+def from_obj_to_xmlrpc(obj_):
+    res = ""
+    if isinstance(obj_,int):
+        res += "<int>%s</int>" % obj_
+        return res
+    elif isinstance(obj_,str):
+        res += "<string>%s</string>" % obj_
+        return res
+    elif isinstance(obj_,dict):
+        res += "<struct>"
+        for k,v in obj_.iteritems():
+            member = {}
+            member["name"]=k
+            member["value"]=from_obj_to_xmlrpc(v)
+            res_1 = "<member>"
+            res_1 += "<name>%(name)s</name>"
+            res_1 += "<value>%(value)s</value>"
+            res_1 += "</member>"
+            res += res_1 % member
+        res += "</struct>"
+        return res
+    elif isinstance(obj_,list):
+        res += "<array><data>"
+        for i in obj_:
+            res += "<value>%s</value>" % from_obj_to_xmlrpc(i)
+        res += "</data></array>"
+        return res
+    else:
+       raise Exception("No valid object")
+
+
 
 class Configuration(object):
     def __init__(self):
@@ -267,8 +310,31 @@
     return redirect(request.fullpath + "/")
 
 
-@app.route("/simple/")
+@app.post('/search')
+@app.post('/search/')
 @auth("list")
+def search():
+    value = ""
+    try:
+        parser = xml.dom.minidom.parse(request.body)
+        member = parser.getElementsByTagName("member")[0]
+        value  = parser.getElementsByTagName("string")[0].childNodes[0].wholeText.strip()
+    except Exception, e:
+        value = ""
+
+    response = []
+    ordering = 0
+    for p in packages():
+        if p.pkgname.count(value) > 0:
+            d = {'_pypi_ordering': ordering, 'version': p.version,
+                 'name': p.pkgname, 'summary': p.fn}
+            response.append(d)
+        ordering += 1
+    res = XMLRPC_RESPONSE_SKELETON \
+        % {"objects":from_obj_to_xmlrpc(response)}
+    return res
+
+@app.route("/simple/")
 def simpleindex():
     links = sorted(get_prefixes(packages()))
     tmpl = """\

</pre>

**Comment by ankostis** [comment]
Of course we are interested for new features, as long as they do not require http-requests upstream or a db.  

Would mind pointing at the points of your patch that you consider "hack"-ish?

**Comment by psaavedra** [comment]
Yes  of course,

- search operation is a XMLRPC request in fact, I just implemented the search request ad-hoc (see XMLRPC_RESPONSE_SKELETON), there is other operations which are in use by pip that they are not implemented. Maybe the best way to do it is using the xmlrpc.server (https://docs.python.org/3/library/xmlrpc.server.html) but this force to use a additional port.

- from_obj_to_xmlrpc is a made by myself translator from built-in data to XML-RPC data model.

**Comment by ankostis** [comment]
Would need a test-case here.

**Comment by ankostis** [comment]
Dear @psaavedra would you mind making a regular pull-request?

**Comment by blade2005** [comment]
@ankostis i'm really interesting in this feature. I'm gonna make a branch and see about get this ready including a test case.

**Comment by janssen** [comment]
I'd kind of like to see this, too.

**Comment by janssen** [comment]
Why in the world does pypi drag in XML-RPC for this simple thing?  You could just send a request the same way (using forms), and send back the response as a pickled Python dict, or as a JSON dict.

**Comment by psaavedra** [comment]
Pull request submitted: https://github.com/pypiserver/pypiserver/pull/115

**Comment by blade2005** [comment]
My pr #114 handles it in a cleaner fashion than the proposed code

**Comment by mplanchard** [comment]
Handled by #114, which has been merged.
