### ISSUE TITLE
1.1.7 and random 503

### ISSUE THREAD

**Issue by coulix** [pypiserver/pypiserver#86]
I tried both with the default bottle webserver and gunicorn (-w4) and every now and then I get a 503 making the mirror unreliable.

I am digging into the code to find more clues.

**Comment by ankostis** [comment]
@coulix, was it a false alarm?

**Comment by ankostis** [comment]
I'm considering it a false alarm.

**Comment by petri** [comment]
This could also be related to #91 that has since been closed.

**Comment by ankostis** [comment]
But this issue was reported before the upgrade of Bottle ``0.11.6-->0.13-dev``,
and #91 relates to `Bottle-0.13-dev`? 
I really don't know for sure, I still get spurious failures in pip-task scripts on Travis.
