### ISSUE TITLE
Add caching for the fallback URL packages

### ISSUE THREAD

**Issue by arcivanov** [pypiserver/pypiserver#90]
1. Add option `--fallback-cache-root` or `-c`
2. If the package is not found locally
    1. Search fallback cache root
    2. If fallback cache root doesn't have the package
        1. Retrieve the package
        2. Store it in the fallback root 
        3. Send it to the requesting client
    3. If fallback cache root does have the package
        1. Check whether package is older than `--cache-control` and if older proceed to 2.ii.a
        2. Otherwise send the cached package to the requesting client

**Comment by ankostis** [comment]
Dear Arcadiy, i think this would require *pypiserver* to make http-requests, correct?

Submitting upstream requests has already been suggested in #23 and the previous maintainer had rejected such functionality, to keep this project small.
I agree with his decision, ed, check #38 for a glimpse of the complexity involved.

Have you tried the workaround suggested also in the docs of this issue #38 ?

**Comment by arcivanov** [comment]
@ankostis I would like to specifically cache the packages transparently, i.e. without having to go to PyPi Central altogether if the package is cached. If this feature is not desired I can just use devpi I guess, but it was a bit too much for my needs to begin with, hence I wanted to see if I could add the functionality here. If this is not desired I might as well go with devpi.

**Comment by ankostis** [comment]
Since what you are actually looking for is a *proxy* pip-server, I would suggest to seriously give *devpi* another try.  It will provide you with the resilience and performance you are looking for.

*pypiserver* has a much more limited scope, just a repository for intranet-produced packages.
